# # Generate a list of variables in the mifs for filtering in extractvars
# dummif <- read.report(mifpaths[1])
# c(
#   getItems(dummif[[1]]$REMIND, 3),
#   getItems(dummif[[1]]$MAgPIE, 3)
# ) %>% write.csv("varlist_magclass.csv", row.names = F)


extractvarsrem <- c(
  "PE (EJ/yr)",
  "PE|+|Biomass (EJ/yr)",
  "PE|+|Coal (EJ/yr)",
  "PE|+|Gas (EJ/yr)",
  "PE|+|Geothermal (EJ/yr)",
  "PE|+|Hydro (EJ/yr)",
  "PE|+|Nuclear (EJ/yr)",
  "PE|+|Oil (EJ/yr)",
  "PE|+|Solar (EJ/yr)",
  "PE|+|Wind (EJ/yr)",
  "PE|Fossil (EJ/yr)",
  "PE|Non-Biomass Renewables (EJ/yr)",
  "Policy Cost|Additional Total Energy System Cost (billion US$2017/yr)",
  "Policy Cost|Consumption + Current Account Loss (billion US$2017/yr)",
  "Policy Cost|Consumption + Current Account Loss|Relative to Reference Consumption + Current Account (%)",
  "Policy Cost|Consumption Loss (billion US$2017/yr)",
  "Policy Cost|Consumption Loss|Relative to Reference Consumption (%)",
  "Policy Cost|GDP Loss (billion US$2017/yr)",
  "Policy Cost|GDP Loss|Relative to Reference GDP (%)",
  "SE (EJ/yr)",
  "FE (EJ/yr)",
  "FE|++|Buildings (EJ/yr)",
  "FE|++|CDR (EJ/yr)",
  "FE|++|Industry (EJ/yr)",
  "FE|++|Transport (EJ/yr)",
  "FE|+|Electricity (EJ/yr)",
  "FE|+|Gases (EJ/yr)",
  "FE|+|Heat (EJ/yr)",
  "FE|+|Hydrogen (EJ/yr)",
  "FE|+|Liquids (EJ/yr)",
  "FE|+|Solids (EJ/yr)",
  "FE|Electricity|Share (%)",
  "SE|Biomass (EJ/yr)",
  "SE|Electricity (EJ/yr)",
  "FE|Transport|+|Electricity (EJ/yr)",
  "FE|Transport|+|Gases (EJ/yr)",
  "FE|Transport|+|Hydrogen (EJ/yr)",
  "FE|Transport|+|Liquids (EJ/yr)",
  "FE|Transport|Liquids|+|Biomass (EJ/yr)",
  "FE|Transport|Liquids|+|Fossil (EJ/yr)",
  "FE|Transport|Liquids|+|Hydrogen (EJ/yr)",
  "FE|Transport|Fuels (EJ/yr)",
  "FE|Transport|Fuels|Share (%)",
  "FE|Transport|Electricity|Share (%)",
  "Emi|CO2 (Mt CO2/yr)",
  "Emi|CO2|+|Energy (Mt CO2/yr)",
  "Emi|CO2|+|Industrial Processes (Mt CO2/yr)",
  "Emi|CO2|+|Land-Use Change (Mt CO2/yr)",
  "Emi|CO2|+|Waste (Mt CO2/yr)",
  "Emi|CO2|+|non-ES CDR (Mt CO2/yr)",
  "Emi|CO2|CDR (Mt CO2/yr)",
  "Emi|CO2|CDR|+|BECCS (Mt CO2/yr)",
  "Emi|CO2|CDR|+|DACCS (Mt CO2/yr)",
  "Emi|CO2|CDR|+|EW (Mt CO2/yr)",
  "Emi|CO2|CDR|+|Land-Use Change (Mt CO2/yr)",
  "Emi|CO2|CDR|+|Materials (Mt CO2/yr)",
  "Emi|CO2|CDR|+|OAE (Mt CO2/yr)",
  "Emi|CO2|CDR|+|Synthetic Fuels CCS (Mt CO2/yr)",
  "Emi|CO2|Cumulated (Mt CO2)",
  "Emi|CO2|Cumulated|CDR (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|BECCS (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|BECCS|Demand Side (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|BECCS|Pe2Se (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|DACCS (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|EW (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|Land-Use Change (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|Materials (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|OAE (Mt CO2)",
  "Emi|CO2|Cumulated|CDR|Synthetic Fuels CCS (Mt CO2)",
  "Emi|CO2|Cumulated|Energy (Mt CO2)",
  "Emi|CO2|Cumulated|Energy and Industrial Processes (Mt CO2)",
  "Emi|CO2|Cumulated|Energy|Demand|Buildings (Mt CO2)",
  "Emi|CO2|Cumulated|Energy|Demand|CDR Sector (Mt CO2)",
  "Emi|CO2|Cumulated|Energy|Demand|Industry (Mt CO2)",
  "Emi|CO2|Cumulated|Energy|Demand|Transport (Mt CO2)",
  "Emi|CO2|Cumulated|Energy|Waste (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Energy|Demand|CDR Sector (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Energy|Demand|Industry (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Energy|Supply|Electricity (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Energy|Supply|Non-electric (Mt CO2)",
  "Emi|CO2|Cumulated|Gross|Waste (Mt CO2)",
  "Emi|CO2|Cumulated|Industrial Processes (Mt CO2)",
  "Emi|CO2|Cumulated|Land-Use Change (Mt CO2)",
  "Emi|CO2|Cumulated|Waste (Mt CO2)",
  "Price|Carbon (US$2017/t CO2)",
  "MAGICC7 AR6|Surface Temperature (GSAT)|33p0th Percentile (K)",
  "MAGICC7 AR6|Surface Temperature (GSAT)|50p0th Percentile (K)",
  "MAGICC7 AR6|Surface Temperature (GSAT)|66p0th Percentile (K)",
  "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile (K)"
)
extractvarsmag <- c(
  "Resources|Land Cover|Forest|+|Natural Forest (million ha)",
  "Resources|Land Cover|Forest|+|Planted Forest (million ha)",
  "Resources|Land Cover|+|Cropland (million ha)",
  "Resources|Land Cover|+|Forest (million ha)",
  "Resources|Land Cover|+|Other Land (million ha)",
  "Resources|Land Cover|+|Pastures and Rangelands (million ha)",
  "Resources|Land Cover|+|Urban Area (million ha)",
  "Resources|Land Cover Change|+|Cropland (million ha wrt 1995)",
  "Resources|Land Cover Change|+|Forest (million ha wrt 1995)",
  "Resources|Land Cover Change|+|Other Land (million ha wrt 1995)",
  "Resources|Land Cover Change|+|Pastures and Rangelands (million ha wrt 1995)",
  "Resources|Land Cover Change|+|Urban Area (million ha wrt 1995)",
  "Resources|Land Cover Conserved|Cropland (million ha)",
  "Resources|Land Cover Conserved|Cropland|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Cropland|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Cropland|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Cropland|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Primary Forest (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Primary Forest|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Primary Forest|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Primary Forest|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Primary Forest|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Secondary Forest (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Secondary Forest|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Secondary Forest|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Secondary Forest|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Forest|Natural Forest|Secondary Forest|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Forest|Planted Forest (million ha)",
  "Resources|Land Cover Conserved|Forest|Planted Forest|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Forest|Planted Forest|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Forest|Planted Forest|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Forest|Planted Forest|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Other Land (million ha)",
  "Resources|Land Cover Conserved|Other Land|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Other Land|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Other Land|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Other Land|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Pastures and Rangelands (million ha)",
  "Resources|Land Cover Conserved|Pastures and Rangelands|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Pastures and Rangelands|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Pastures and Rangelands|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Pastures and Rangelands|Restored cumulatively (million ha since 2025)",
  "Resources|Land Cover Conserved|Urban Area (million ha)",
  "Resources|Land Cover Conserved|Urban Area|+|Protected (million ha)",
  "Resources|Land Cover Conserved|Urban Area|+|Restored (million ha)",
  "Resources|Land Cover Conserved|Urban Area|Restored annually (million ha/yr)",
  "Resources|Land Cover Conserved|Urban Area|Restored cumulatively (million ha since 2025)",
  "Resources|Carbon (Mt C)",
  "Resources|Carbon|+|Litter (Mt C)",
  "Resources|Carbon|+|Soil (Mt C)",
  "Resources|Carbon|+|Vegetation (Mt C)",
  "Emissions|CO2|Land RAW (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|++|Above Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|++|Below Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|+|Indirect (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|+|Land-use Change (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Indirect|++|Above Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Indirect|++|Below Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|++|Above Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|++|Below Ground Carbon (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Deforestation (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Forest degradation (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Other land conversion (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Peatland (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Regrowth (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Residual (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Soil (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Timber (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|+|Wood Harvest (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Deforestation|+|Cropland Tree Cover (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Deforestation|+|Forestry plantations (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Deforestation|+|Primary forests (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Deforestation|+|Secondary forests (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Forest degradation|+|Primary forests (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Forest degradation|+|Secondary forests (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Peatland|+|Negative (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Peatland|+|Positive (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|CO2-price AR (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|Cropland Tree Cover (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|NPI_NDC AR (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|Other Land (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|Secondary Forest (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|+|Timber Plantations (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|CO2-price AR|+|Natural Forest (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Regrowth|CO2-price AR|+|Plantation (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Residual|+|Negative (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Residual|+|Positive (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Soil|++|Emissions (Mt CO2/yr)",
  "Emissions|CO2|Land RAW|Land-use Change|Soil|++|Withdrawals (Mt CO2/yr)",
  "Emissions|CO2|Land|Cumulative (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|++|Above Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|++|Below Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|+|Indirect (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|+|Land-use Change (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Indirect|++|Above Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Indirect|++|Below Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|++|Above Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|++|Below Ground Carbon (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Deforestation (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Other land conversion (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Peatland (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Regrowth (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Residual (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Soil (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Timber (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|+|Wood Harvest (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|+|Forest degradation (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|+|Permanent deforestation (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Forest degradation|+|Primary forests (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Forest degradation|+|Secondary forests (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Permanent deforestation|+|Cropland Tree Cover (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Permanent deforestation|+|Forestry plantations (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Permanent deforestation|+|Primary forests (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Deforestation|Permanent deforestation|+|Secondary forests (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|CO2-price AR (Gt CO2/yr)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|Cropland Tree Cover (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|NPI_NDC AR (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|Other Land (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|Secondary Forest (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|+|Timber Plantations (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|CO2-price AR|+|Natural Forest (Gt CO2)",
  "Emissions|CO2|Land|Cumulative|Land-use Change|Regrowth|CO2-price AR|+|Plantation (Gt CO2)",
  "Productivity|Yield-increasing technological change crops (%/yr)",
  "Productivity|Yield-increasing technological change managed pastures (%/yr)",
  "Productivity|Landuse Intensity Indicator Tau (Index)",
  "SDG|SDG01|Per-capita income (USD05/cap/yr)",
  "SDG|SDG02|Agricultural commodity price index wrt 2020 (1)",
  "SDG|SDG02|Food availability (kcal/cap/day)",
  "SDG|SDG02|Food expenditure share (income)",
  "SDG|SDG02|Investment in AgR&D (million USD05/yr)",
  "SDG|SDG02|Prevalence of obesity|Children (million)",
  "SDG|SDG02|Prevalence of underweight (million)",
  "SDG|SDG02|Prevalence of underweight|Children (million)",
  "SDG|SDG03|Consumption of alcohol (kcal/cap/day)",
  "SDG|SDG03|Prevalence of obesity (million)",
  "SDG|SDG03|Prevalence of obesity|Children (million)",
  "SDG|SDG03|Prevalence of overweight (million)",
  "SDG|SDG03|Prevalence of overweight|Children (million)",
  "SDG|SDG06|Agricultural water use (km3/yr)",
  "SDG|SDG06|Fertilizer use (Mt N/yr)",
  "SDG|SDG06|Nitrogen surplus on cropland (Mt N/yr)",
  "SDG|SDG12|Food loss (Mt DM/yr)",
  "SDG|SDG12|Food waste (kcal/cap/day)",
  "SDG|SDG12|Food waste total (Mt DM/yr)",
  "SDG|SDG12|Material footprint (tDM/capita/yr)",
  "SDG|SDG15|Afforestation (million ha)",
  "SDG|SDG15|Biological nitrogen fixation on cropland (Mt N/yr)",
  "SDG|SDG15|Forest share (share of total land)",
  "SDG|SDG15|Industrial and intentional biological fixation of N (Mt N/yr)",
  "SDG|SDG15|Non-agricultural land share (share of total land)",
  "SDG|SDG15|Other natural land share (share of total land)",
  "SDG|SDG15|Primary forest share (share of total land)",
  "SDG|SDG15|Terrestrial biodiversity (index)"
)