require(tidyverse)
require(quitte)
require(magclass)
require(lucode2)
require(geomtextpath)
require(ggpubr)
require(ggpp)
require(GGally)
options(width = 140)
# Model colors
source("colors_models_v1.R")
# REMIND-MAgPIE variables to keep from the MIF
# extractvarsrem and extractvarsmag variables come from here
source("extractvars_v1.R")

# Master setup for choosing scenarios in plots
mlowbudget <- 540
mhigbudget <- 920
musebudget <- 840 # Closest to 2K67 in most models in AR6 (800-880)

# Temporary, generated by postprocess_gang_v5 script
# climfname <- "qlclim_gangv03sub600_E25v05p1.rds"
# climfname <- "qlclimadj_gangv03sub600_E25v05p1.rds"
climfname <- "qlclimadj_gangv04sub600_E25v05p1.rds"


# Harmonized emission file
harmfname <- "ESM2025v05p1_full_harmonized_clean.csv"

# mifpaths <- Sys.glob("output/*-rem-5/REMIND_generic*.mif")
mifpaths <- Sys.glob("clusterdown_v05p1/REMIND_generic*.mif")
mifpaths <- mifpaths[str_detect(mifpaths, "withoutPlus", negate = TRUE)]

# mifpath <- mifpaths[1]
read_filtmif <- function(mifpath) {
  inmag <- read.report(mifpath)
  scen <- names(inmag)
  frem <- inmag[[1]]$REMIND[, , extractvarsrem]
  fmag <- inmag[[1]]$MAgPIE[, , extractvarsmag]
  fmif <- rbind(as.quitte(frem), as.quitte(fmag)) %>%
    mutate(scenario = scen, model = "REMIND-MAgPIE")
  return(fmif)
}

# ====================================================================
# Reading all MIFs with only selected REMIND-MAgPIE data
# rerun_bigmif <- TRUE
rerun_bigmif <- FALSE
if (rerun_bigmif || !file.exists("inbigmif.rds")) {
  cat("!!!!!!!! Re-running and caching bigmif !!!!!!!!!!\n")
  miflist <- lapply(mifpaths, read_filtmif)
  inbigmif <- bind_rows(miflist)
  saveRDS(inbigmif, "inbigmif.rds")

  # Adding extended scenario info columns
  allscens <- inbigmif %>%
    select(scenario) %>%
    unique()
  sceninfo <- allscens %>%
    separate(scenario, c("vtag", "lsm", "ssp", "policy"), sep = "-", remove = F) %>%
    select(-vtag) %>%
    mutate(cbudget = ifelse(str_detect(policy, "Budg"), str_extract(policy, "[0-9][0-9][0-9]"), "NA")) %>%
    mutate(cbudget = as.numeric(cbudget))

  bigmif <- inbigmif %>%
    left_join(sceninfo)

  # Adding cumulative variables
  cumvars <- c(
    "Emi|CO2",
    "Emi|CO2|+|Land-Use Change",
    "Emi|CO2|+|Energy",
    "Emi|CO2|+|Industrial Processes",
    "Emi|CO2|+|Land-Use Change",
    "Emi|CO2|+|Waste",
    "Emi|CO2|+|non-ES CDR",
    "Emi|CO2|CDR",
    "Emi|CO2|CDR|+|BECCS",
    "Emi|CO2|CDR|+|Land-Use Change"
  )
  cummif <- bigmif %>%
    filter(variable %in% cumvars) %>%
    group_by_at(vars(-period, -value)) %>%
    arrange(period, .by_group = T) %>%
    mutate(dt = period - lag(period)) %>%
    filter(period >= 2020) %>%
    mutate(value = cumsum(value * dt)) %>%
    mutate(variable = paste0(variable, "|Cum")) %>%
    select(-dt) %>%
    ungroup()
  bigmif <- bind_rows(bigmif, cummif)
  
  # bigmif %>% select(variable) %>% unique %>% filter(str_detect("Harmonized"))
  
  bigmif %>%
    select(variable) %>%
    unique() %>%
    write.csv("varlist_bigmif.csv", row.names = F)

  saveRDS(sceninfo, "sceninfo.rds")
  saveRDS(bigmif, "bigmif.rds")
} else {
  cat("!!!!!!!! Reading cached bigmif !!!!!!!!!!\n")
  # inbigmif <- readRDS("inbigmif.rds")
  sceninfo <- readRDS("sceninfo.rds")
  bigmif <- readRDS("bigmif.rds")
}
# inbigmif %>% select%>% select(variable) %>%

object.size(bigmif) %>% print(unit = "Mb")

# ====================================================================
# Append climate MIF and harmonized emissions in a separate mixbigmif variable
rerun_mixbigmif <- FALSE
# rerun_mixbigmif <- TRUE
if (rerun_mixbigmif || !file.exists("cache_mixbigmif.rds")) {
  cat("!!!!!!!! Re-running and caching mixbigmif !!!!!!!!!!\n")
  inclimmif <- readRDS(climfname)
  
  # inclimmif %>%
  #   left_join(select(sceninfo, scenario, lsm)) %>%
  #   filter(
  #     variable == "Surface Air Temperature Change",
  #     period == 2050,
  #     quant == "q50"
  #     ) %>% 
  #   select(model,lsm) %>% distinct %>% View
  # 

  # Keep only scenario(lsm)-model combinations that are either
  # compatible or AR6.
  inclimmif <- inclimmif %>%
    left_join(select(sceninfo, scenario, lsm)) %>%
    filter((model == lsm | model == "AR6"))

  # Adjusting GSAT so that the median matches 0.85K in 1995-2014
  # As in Kikstra et al.
  # TODO: Do this step at the individual run level. Doing it after
  # evaluating the quantiles is very close but not necessarily the same 
  adjfacs <- inclimmif %>%
    filter(
      variable %in% c("Surface Air Temperature Change"),
      quant == "q50"
      ) %>%
      filter(between(period, 1995, 2014)) %>%
      group_by(across(c(-period,-value))) %>%
      summarise(value = mean(value, na.rm = T)) %>%
      ungroup() %>%
      mutate(adjfac = 0.85 - value) %>%  
      select(model, scenario, adjfac)

  tempclimmif <- inclimmif %>%
    filter(variable %in% c("Surface Air Temperature Change")) %>%
    left_join(adjfacs) %>%
    mutate(value = value + adjfac) %>%
    select(-adjfac)

  inclimmif <- inclimmif %>%
      filter(!(variable %in% c("Surface Air Temperature Change"))) %>%
      bind_rows(tempclimmif)  

  mixbigmif <- inclimmif %>%
    mutate(variable = paste0(variable, "|", quant)) %>%
    mutate(region = "World") %>%
    select(-quant) %>%
    left_join(sceninfo) %>%
    bind_rows(bigmif, .)

  # Harmonized emissions
  inharmmif <- read.delim(harmfname, sep = ",") %>%
    select(-X, -exclude) %>%
    pivot_longer(
      cols = starts_with("X"),
      names_pattern = "X(.*)",
      names_to = "period",
      values_to = "value"
    ) %>%
    mutate(period = as.integer(str_sub(period, 1L, 4L))) %>%
    mutate(variable = paste0("Harmonized|", variable)) %>%
    calc_addVariable(
      `Harmonized|Emissions|CO2` = "`Harmonized|Emissions|CO2|MAGICC AFOLU` + `Harmonized|Emissions|CO2|MAGICC Fossil and Industrial`",
      unit = "Mt CO2/yr"
    ) %>%
    left_join(sceninfo)

  mixbigmif <- mixbigmif %>%
    bind_rows(., inharmmif)
  
  
  # ====================================================================
  # Calculating indicators that need variables from different sources ==
  cumvars <- c(
    "Harmonized|Emissions|CO2",
    "Harmonized|Emissions|CO2|MAGICC AFOLU",
    "Harmonized|Emissions|CO2|MAGICC Fossil and Industrial"
  )
  cummif <- mixbigmif %>%
    filter(variable %in% cumvars) %>%
    group_by_at(vars(-period, -value)) %>%
    arrange(period, .by_group = T) %>%
    mutate(dt = period - lag(period)) %>%
    filter(period >= 2020) %>%
    mutate(value = cumsum(value * dt)) %>%
    mutate(variable = paste0(variable, "|Cum")) %>%
    select(-dt) %>%
    ungroup()

  mixbigmif <- mixbigmif %>%
    bind_rows(., cummif)

  # Equivalent CO2 emissions from atmospheric concentrations ================

  # Filter and save in a variable, as it takes some time to filter
  atmmif <- mixbigmif %>%
    filter(str_detect(variable, "Atmospheric Concentrations\\|CO2"))
  refatm <- atmmif %>%
    filter(period == 2020) %>%
    select(-period) %>%
    rename(valref = value)
  # Conversion factor 1 ppm = 2.124GtC taken from
  # Friedlingstein et al., 2024, Table 1, also 1 GtC = 3.664 GtCO2
  eqemif <- left_join(atmmif, refatm) %>%
    filter(period >= 2020) %>%
    mutate(value = value - valref) %>%
    mutate(variable = str_replace(
      variable,
      "Atmospheric Concentrations\\|CO2\\|",
      "Atmospheric Concentrations|CO2|EqEm2020|"
    )) %>%
    mutate(unit = "GtCO2") %>%
    select(-valref) %>%
    mutate(value = value * 2.124 * 3.664 * 1e3) # ppm to GtC, GtC to GtCO2, GtCO2 to MtCO2

  # Airborne fraction ===============================
  abfmif <- cummif %>%
    filter(variable == "Harmonized|Emissions|CO2|Cum") %>%
    mutate(period = period + 1) %>% # Shift by one year to approximate emissions causing concentration changes
    select(-model, -unit, -variable) %>%
    rename(valuemi = value) %>%
    left_join(eqemif, .) %>%
    mutate(value = value / valuemi) %>%
    mutate(variable = str_replace(
      variable,
      "Atmospheric Concentrations\\|CO2\\|EqEm2020\\|",
      "Airborne Fraction|Since2020|"
    )) %>%
    select(-valuemi)

  mixbigmif <- mixbigmif %>%
    bind_rows(., eqemif, abfmif)

  mixbigmif %>%
    select(variable) %>%
    unique() %>%
    write.csv("varlist_mixbigmif.csv", row.names = F)

  saveRDS(mixbigmif, "cache_mixbigmif.rds")
} else {
  cat("!!!!!!!! Reading cached mixbigmif from file !!!!!!!!!!\n")
  mixbigmif <- readRDS("cache_mixbigmif.rds")
}

object.size(mixbigmif) %>% print(unit = "Mb")

# ====================================================================
# Mixed MAGICC and REMIND-MAgPIE only plots
# ====================================================================
usebudget <- musebudget
useyear <- 2050

# Original temperature comparison vs. LUC emissions
tmpclim <- mixbigmif %>%
  filter(variable == "Surface Air Temperature Change|q50") %>%
  filter(lsm == model | model == "AR6") %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated_to_DVGM", model))

tmpmit <- mixbigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  # select(scenario, lsm, value) %>%
  select(scenario, lsm, value, period) %>%
  rename(valuemit = value)

tmpclim %>%
  # select(scenario, model, lsm, value) %>%
  select(scenario, model, lsm, value,period) %>%
  left_join(tmpmit) %>%
  ggplot(aes(
    x = valuemit, y = value,
    group = lsm,
    color = lsm, shape = model
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  facet_wrap(~period) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    y = paste0("GSAT ", useyear, " 50th perc. [K]"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  )
ggsave(paste0("temp_Xlucemi", "_", usebudget, "_", useyear, ".png"))


# Original temperature comparison vs. LUC emissions + Airborne fraction
tmpclim <- mixbigmif %>%
  filter(variable %in% c(
    "Surface Air Temperature Change|q67",
    "Airborne Fraction|Since2020|q67"

  )) %>%
  filter(lsm == model | model == "AR6") %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated to DVGM", "AR6 Ensemble"))

tmpmit <- mixbigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  select(scenario, lsm, value, period) %>%
  rename(valuemit = value)

tmpclim %>%
  select(scenario, variable, model, lsm, value, period) %>%
  # select(scenario, variable, model, lsm, value) %>%
  left_join(tmpmit) %>%
  mutate(variable = case_when(
    variable == "Surface Air Temperature Change|q67" ~ "GSAT",
    variable == "Airborne Fraction|Since2020|q67" ~ "Airborne Fraction of emissions since 2020",
    TRUE ~ variable
  )) %>%
  # filter(model == "Calibrated to DVGM", period == 2050)
  ggplot(aes(
    x = valuemit, y = value,
    group = lsm,
    color = lsm, shape = model
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  facet_wrap(~variable+period, scales = "free") +
  scale_color_manual(values = modelcolors) +
  labs(
    x = paste0("Cumulative LUC emissions since 2020 [GtCO2]"),
    y = paste0("GSAT [K] or Airborne Fraction (67th perc.)"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  )
# ggsave(paste0("tempandaf_Xlucemi", "_", usebudget, "_", useyear, ".png"), width = 10, height = 4)
ggsave(paste0("tempandaf_Xlucemi", "_", usebudget, "_", "bothyears", ".png"), width = 9, height = 7)

# DVGM vs. ensemble uncertainty
mixbigmif %>%
  filter(variable %in% c(
    "Surface Air Temperature Change|q50",
    "Surface Air Temperature Change|q67",
    "Surface Air Temperature Change|q90",
    "Surface Air Temperature Change|q10"
  )) %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated to DVGM", "AR6 Ensemble")) %>%
  mutate(variable = str_remove(variable, "Surface Air Temperature Change\\|")) %>%
  # group_by(variable,model,period) %>%
  # summarise(min = min(value), max = max(value), mean = mean(value))
  ggplot(aes(x = model, y = value, color = variable)) +
  # geom_jitter(size = 0.5) +
  geom_boxplot() +
  facet_wrap(~period, scales = "free") +
    labs(
    x = "",
    y = paste0("GSAT [K]"),
    color = "Quantile from 600\nclimate parametrizations:"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal", 
    legend.title.position = "top",
    legend.justification = "center"
    ) 
ggsave(paste0("tempvsquantiles", "_", usebudget, "_", "bothyears", ".png"), width = 6, height = 5)


# Diff temperature between calibrations vs. LUC emissions
# Should be (Calibrated to DVGM - AR6). Then we get positive differences
# when the calibrated model is warmer than AR6 average.
# The hypothesis is that LOWER (more negative) LUC emissions are
# correlated with LOWER (more negative) temperature differences.
tmpclim <- mixbigmif %>%
  filter(variable == "Surface Air Temperature Change|q67") %>%
  filter(lsm == model | model == "AR6") %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated_to_DVGM", model)) %>%
  # select(scenario,model,lsm,value) %>%
  select(scenario, model, cbudget, period, lsm, value) %>%
  pivot_wider(names_from = model, values_from = value) %>%
  mutate(value = `Calibrated_to_DVGM` - `AR6`) %>%
  select(-`Calibrated_to_DVGM`, -`AR6`)

tmpmit <- mixbigmif %>%
  filter(
    region %in% c("World", "GLO"),
    variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  mutate(value = value * 1e-3) %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  # select(scenario,lsm,value) %>%
  select(scenario, model, cbudget, period, lsm, value) %>%
  rename(valuemit = value)

# Single plot for single budget and year
tmpclim %>%
  filter(period %in% c(2050,2100)) %>%
  filter(cbudget %in% c(usebudget)) %>%
  left_join(tmpmit) %>%
  ggplot(aes(x = valuemit, y = value, color = lsm)) +
  geom_point(size = 3) +
  # geom_smooth(se = F, method = lm, color = "grey30") +
  # geom_line() +
  # geom_hline(yintercept = 0) +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = paste0("Cost-effective cum. LUC emissions since 2020 [GtCO2]"),
    y = paste0("Diff. (Calibrated to DVGM - AR6 Ensemble)\nGSAT ", useyear, " 67th perc. [K]"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  facet_wrap(~ period + cbudget, ncol = 2, scales = "free_x")

ggsave(paste0("temp_diff_Xlucemi", "_", usebudget, "_years.png"), height = 4, width = 8)


# Facet
tmpclim %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget %in% c(620, 720)) %>%
  left_join(tmpmit) %>%
  ggplot(aes(x = valuemit, y = value, color = lsm)) +
  geom_point(size = 3) +
  # geom_line() +
  geom_hline(yintercept = 0) +
  geom_smooth(se = F, method = "lm") +
  theme_bw() +
  labs(
    x = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    y = paste0("Diff. (Calibrated to DVGM - AR6 Ensemble)\nGSAT ", useyear, " 67th perc. [K]"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  facet_wrap(~ period + cbudget)

ggsave(paste0("temp_diff_Xlucemi", "_facet_", ".png"))

# Just usebudget
tmpclim %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget %in% c(usebudget)) %>%
  left_join(tmpmit) %>%
  ggplot(aes(x = valuemit, y = value, color = lsm)) +
  geom_point(size = 3) +
  # geom_smooth(se = F, method = lm, color = "grey30") +
  stat_smooth(method = "lm", formula = y ~ x) +
  stat_regline_equation(
    aes(label = paste(..eq.label.., ..adj.rr.label.., sep = "~~~~")),
    formula = formula
  ) +
  geom_hline(yintercept = 0) +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = paste0("Cost-effective cum. LUC emissions since 2020 [GtCO2]"),
    y = paste0("Diff. (AR6 Ensemble - Calibrated to DVGM)\nGSAT ", " 67th perc. [K]"),
    # shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  facet_wrap(~ period + cbudget, ncol = 1)

ggsave(paste0("temp_diff_Xlucemi", "_", usebudget, "_years.png"), height = 7, width = 6)


# Temp and CO2 concentrations ==============================================
tmpclim <- mixbigmif %>%
  filter(variable %in% c(
    "Surface Air Temperature Change|q50",
    "Atmospheric Concentrations|CO2|q50"
  )) %>%
  filter(lsm == model | model == "AR6") %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated_to_DVGM", model)) %>%
  # select(scenario,model,lsm,value) %>%
  select(scenario, model, variable, cbudget, period, lsm, value) %>%
  pivot_wider(names_from = model, values_from = value) %>%
  mutate(value = `Calibrated_to_DVGM` - `AR6`) %>%
  select(-`Calibrated_to_DVGM`, -`AR6`)

# Just usebudget
tmpclim %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget %in% c(usebudget)) %>%
  left_join(tmpmit) %>%
  ggplot(aes(x = valuemit, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_smooth(se = F, method = lm, color = "grey30") +
  # geom_line() +
  geom_hline(yintercept = 0, color = "grey50", lty = "dashed") +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = paste0("Cost-effective cum. LUC emissions since 2020 [GtCO2]"),
    y = paste0("Diff. (AR6 Ensemble - Calibrated to DVGM)\n50th perc. GSAT [K] or Atmospheric [CO2] [ppm]"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  facet_wrap(~ variable + period, ncol = 2, scales = "free_y")

ggsave(paste0("temp_diff_co2_Xlucemi", "_", usebudget, "_years.png"), height = 7, width = 10)

# Temp several quantiles ==============================================
tmpclim <- mixbigmif %>%
  filter(variable %in% c(
    "Surface Air Temperature Change|q50",
    "Surface Air Temperature Change|q10",
    "Surface Air Temperature Change|q90"
  )) %>%
  filter(lsm == model | model == "AR6") %>%
  # filter(cbudget == usebudget, period == useyear) %>%
  mutate(model = ifelse(model != "AR6", "Calibrated_to_DVGM", model)) %>%
  # select(scenario,model,lsm,value) %>%
  select(scenario, model, variable, cbudget, period, lsm, value) %>%
  pivot_wider(names_from = model, values_from = value) %>%
  mutate(value = `Calibrated_to_DVGM` - `AR6`) %>%
  select(-`Calibrated_to_DVGM`, -`AR6`)

# Just usebudget
tmpclim %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget %in% c(usebudget)) %>%
  left_join(tmpmit) %>%
  mutate(variable = str_replace_all(variable, "Surface Air Temperature Change", "GSAT")) %>%
  ggplot(aes(x = valuemit, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_smooth(se = F, method = lm, color = "grey30") +
  # geom_line() +
  geom_hline(yintercept = 0, color = "grey50", lty = "dashed") +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = paste0("Cost-effective cum. LUC emissions since 2020 [GtCO2]"),
    y = paste0("Diff. (Calibrated to DVGM - AR6 Ensemble) GSAT [K]"),
    shape = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  scale_color_manual(values = modelcolors) +
  facet_wrap(~ period + variable, ncol = 3)

ggsave(paste0("temp_diff_quantiles_Xlucemi", "_", usebudget, "_years.png"), height = 7, width = 9)


# ====================================================================
# Test picking temperature target scenario
# ====================================================================
# Net-zero year from harmonized emissions
nzmif <- mixbigmif %>%
  filter(variable == "Harmonized|Emissions|CO2") %>%
  filter(!is.na(cbudget)) %>%
  group_by(scenario) %>%
  select(scenario, period, value) %>%
  mutate(value = abs(value)) %>%
  filter(value == min(value)) %>%
  ungroup() %>%
  rename(nzyearharm = period) %>%
  select(scenario, nzyearharm)

# Net-zero year from raw emissions
nzmifraw <- bigmif %>%
  filter(region == "GLO") %>%
  filter(variable == "Emi|CO2") %>%
  filter(!is.na(cbudget)) %>%
  group_by(scenario) %>%
  select(scenario, period, value) %>%
  mutate(value = abs(value)) %>%
  filter(value == min(value)) %>%
  ungroup() %>%
  rename(nzyearraw = period) %>%
  select(scenario, nzyearraw)

illumodels <- c("LPJwsl", "ORCHIDEE", "LPJml")

mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))

mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(type = ifelse(model == "AR6","AR6 Ensemble", "Calibrated to DVGM")) %>%
  filter(cbudget == 840) %>%
  ggplot(aes(x = period, y = value, color = type, group = interaction(lsm,model))) +
  geom_line() +
  facet_wrap(~cbudget)

mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, variable, value, cbudget, lsm, caltype) %>%
  group_by(scenario, variable, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT (50th or 67th percentile) [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("temp_budgets_AR6_peak.png", width = 7, height = 8)
ggsave("temp_budgets_AR6_peak.svg", width = 7, height = 8)




mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(model,scenario, period, variable, value, cbudget, lsm, caltype) %>%
  # group_by(scenario, caltype) %>%
  # filter(value == max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == 2100) %>%
  # select(model) %>% unique
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("2100 GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("temp_budgets_AR6_EoC.png", width = 7, height = 8)
ggsave("temp_budgets_AR6_EoC.svg", width = 7, height = 8)


mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, variable, value, cbudget, lsm, caltype) %>%
  group_by(scenario, variable, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  # filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT (50th or 67th percentile) [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("temp_budgets_both_peak.png", width = 7, height = 8)
ggsave("temp_budgets_both_peak.svg", width = 7, height = 8)


mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(model,scenario, period, variable, value, cbudget, lsm, caltype) %>%
  # group_by(scenario, caltype) %>%
  # filter(value == max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == 2100) %>%
  # select(model) %>% unique
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  # filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("2100 GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("temp_budgets_both_EoC.png", width = 7, height = 8)
ggsave("temp_budgets_both_EoC.svg", width = 7, height = 8)


# Target budget estimation ===========================

ttarget <- 1.7
tbudgetinfo <- mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q50"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "tbudgetdvgm", "tbudgetar6")) %>% #View
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>% #View
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  select(-period) %>%
  # rename(period = cbudget) %>%
  # interpolate_missing_periods(seq(400, 800, 1), expand.values = F) %>%
  group_by(caltype, lsm) %>%
  # mutate(diff = (abs(value - ttarget))) %>%
  mutate(diff = (-1 * (value - ttarget))) %>%
  mutate(diff = ifelse(diff < 0, NA, diff)) %>% #View
  filter(diff == min(diff, na.rm = T)) %>%
  select(caltype, lsm, cbudget) %>%
  pivot_wider(names_from = caltype, values_from = cbudget)
tbudgetinfo

tbudgetmif <- tbudgetinfo %>%
  pivot_longer(-lsm, names_to = "variable") %>%
  mutate(model = ifelse(variable == "tbudgetar6", "AR6", lsm)) %>%
  mutate(variable = "Carbon budget to 1.7C 50th perc.")

mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q50"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>% 
  # filter(lsm == model | model == "AR6") %>%
  # mutate(caltype = ifelse(model != "AR6", "tbudgetdvgm", "tbudgetar6")) %>% #View
  select(scenario, model, period, value, cbudget, lsm) %>% 
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, model) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>% #View
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  select(-period) %>%
  # rename(period = cbudget) %>%
  # interpolate_missing_periods(seq(400, 800, 1), expand.values = F) %>%
  group_by(model, lsm) %>%
  # mutate(diff = (abs(value - ttarget))) %>%
  mutate(diff = (-1 * (value - ttarget))) %>%
  mutate(diff = ifelse(diff < 0, NA, diff)) %>% #View
  filter(diff == min(diff, na.rm = T)) %>%
  select(model, lsm, cbudget) %>%
  pivot_wider(names_from = model, values_from = cbudget)



mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  group_by(caltype, lsm) %>%
  summarise(in_range = any(value >= ttarget)) %>%
  pivot_wider(names_from = caltype, values_from = in_range)

# TCRE-like estimates =======================================
pktemp <- mixbigmif %>%
  filter(variable == "Surface Air Temperature Change|q50") %>%
  group_by(model,scenario,lsm) %>%
  filter(value == max(value, na.rm = T)) %>% 
  ungroup %>%
  filter(str_detect(policy,"PkBudg")) %>%
  mutate(variable == "Peak Temperature|q50")
  
xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

left_join(pktemp, xmif)


p1 <- pktemp %>%
  filter(cbudget <= 900) %>%
  filter(model != "AR6") %>%
  ggplot(aes(x = cbudget, y = value, color = model, group = interaction(model,lsm))) +
  geom_point() +
  geom_smooth(se = F, method = lm) +
  geom_hline(yintercept = 1.7) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Peak cumulative emissions [GtCO2]",
    y = "GSAT 50th percentile [K]",
    color = "DVGM"

        )

p2 <- left_join(pktemp, xmif) %>%
  filter(cbudget <= 900) %>%
  filter(model != "AR6") %>%
  ggplot(aes(x = xvar, y = value, color = model, group = interaction(model,lsm))) +
  geom_point() +
  geom_smooth(se = F, method = lm) +
  geom_hline(yintercept = 1.7) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions in 2050 [GtCO2]",
    y = "GSAT 50th percentile [K]",
    color = "DVGM"
    
  )


cowplot::plot_grid(p1,p2)



# ====================================================================
# Summary plots with target budget comparison =================
# ====================================================================

# Basic summary plots
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      "Resources|Land Cover|+|Forest",
      "Emi|CO2|+|Energy|Cum",
      "Emi|CO2|+|Land-Use Change|Cum",
      "Price|Carbon"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  # filter(period %in% c(2050, 2100)) %>%
  left_join(tbudgetinfo) %>%
  mutate(model = case_when( # Caveat: This doesn't work if both budgets are the same
    cbudget == tbudgetar6 ~ "Climate-AR6",
    cbudget == tbudgetdvgm ~ "Climate-DVGM ",
    TRUE ~ NA
  )) %>%
  filter(!is.na(model)) %>%
  ggplot(aes(x = lsm, y = value, color = lsm, shape = model, group = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  labs(
    x = "",
    y = "",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
  )
ggsave("summary_basic_tbudget2K67.png", width = 10, height = 8)

# Summary with same variables as previous section
xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

# mixbigmif %>%
#   filter(region %in% c("GLO", "World")) %>%
#   filter(variable == "Price|Carbon") %>%
#   filter(period == 2050) %>%
#   View

# C_ESM2025v05-LPJwsl-SSP2-PkBudg540-rem-5

combmif <- mixbigmif %>%
  filter(
    # cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>%
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest Area in 2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2050" ~ "Cum. Gross FFI CO2 emi. in 2050 [GtCO2]",
    variable == "Price|Carbon in 2050" ~ "Carbon Price in 2050 [$/tCO2]",
    # variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2050" ~ "Total cum. CDR in 2050 [$/tCO2]",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>% 
  left_join(tbudgetinfo) #%>% #View

combmifar6 <- combmif %>%
  mutate(model = case_when( 
    cbudget == tbudgetar6 ~ "AR6 Ensemble",
    # cbudget == tbudgetdvgm ~ "Calibrated to DVGM",
    TRUE ~ NA
  )) %>% #select(model) %>% unique
  filter(!is.na(model)) 
combmifdvgm <- combmif %>%
  mutate(model = case_when(
    # cbudget == tbudgetar6 ~ "AR6 Ensemble",
    cbudget == tbudgetdvgm ~ "Calibrated to DVGM",
    TRUE ~ NA
  )) %>% #select(model) %>% unique
  filter(!is.na(model)) 


bind_rows(combmifar6, combmifdvgm)%>% #View#select(lsm) %>% unique
  bind_rows(
    tbudgetmif %>%
      mutate(model = ifelse(model == "AR6","AR6 Ensemble","Calibrated to DVGM")) %>%
      left_join(rename(xmif, value = cbudget))
    ) -> dum#%>%
dum %>%    
  mutate(variable = str_replace(variable, " in 20", "\n20")) %>%
  mutate(variable = str_replace(variable, " to 1.7C", "\nto 1.7°C")) %>%
  # ggplot(aes(x = lsm, y = value, color = lsm, shape = model, group = lsm)) +
  ggplot(aes(x = xvar, y = value, color = lsm, shape = model)) +
  geom_point(size = 3) +
  # geom_line() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # coord_flip() +
  # facet_wrap(~ variable + model, scales = "free", ncol = 2) +
  facet_grid(variable ~ model, scales = "free") +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  labs(
    x = "Cost-effective cum. LUC emissions since 2020 [GtCO2]",
    y = "",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
  )
ggsave("summary_tbudget_1p7K50_dvgm.png", width = 8, height = 10)

dum %>% 
  group_by(variable, model) %>%
  summarise(min = min(value), max = max(value), dif = max-min,mean = min(value), dpc = 100*dif/mean)

# Illustrative Stacked bar =================================
# Adjusting cumulative emissions to be since 2020 (default 2005)
tempcumvars <- c(
    # "Emi|CO2|Cumulated",
    # "Emi|CO2|Cumulated|Energy and Industrial Processes",
    # "Emi|CO2|Cumulated|Land-Use Change"
    "Emi|CO2|Cum",
    "Emi|CO2|+|Energy|Cum",
    "Emi|CO2|+|Industrial Processes|Cum",
    "Emi|CO2|+|Land-Use Change|Cum",
    "Emi|CO2|+|Waste|Cum",
    "Emi|CO2|+|non-ES CDR|Cum"
  )
temp2020 <- bigmif %>%
  filter(variable %in% tempcumvars, region == "GLO") %>% 
  filter(period == 2020) %>%
  select(scenario, variable, value) %>%
  rename(val2020 = value)
tempcumdata <- bigmif %>%
  filter(variable %in% tempcumvars, region == "GLO") %>%
  mutate(value = value*1e-3) #%>%
  # left_join(temp2020) %>%
  # mutate(value = value - val2020)

tempcumdata <-
  tempcumdata %>%
  calc_addVariable(
    `Emi|CO2|+|Energy and Industrial Processes|Cum` = "`Emi|CO2|+|Energy|Cum` + `Emi|CO2|+|Industrial Processes|Cum`",
    only.new = FALSE
    ) #%>% select(variable) %>% unique

pkemidata <- tempcumdata %>%
    filter(variable == "Emi|CO2|Cum", region == "GLO") %>%
  # filter(variable == "Emi|CO2|Cumulated", region == "GLO") %>%
  group_by(scenario) %>% 
  filter(value == max(value)) %>%
  select(scenario, value, period) %>%
  # mutate(value = value*1e-3) %>%
  rename(pkemival = value, pkemiyear = period)

# temppointdata <- 

temppkdata <-
  tempcumdata %>%
  filter(variable %in% c(
    # "Emi|CO2|Cumulated|Energy and Industrial Processes",
    # "Emi|CO2|Cumulated|Land-Use Change"
    "Emi|CO2|Cum",
    "Emi|CO2|+|Land-Use Change|Cum",
    "Emi|CO2|+|Energy and Industrial Processes|Cum"
  )) %>% #select(variable) %>% unique
  left_join(pkemidata) %>%
  filter(period == pkemiyear) %>%
  left_join(tbudgetinfo) %>%
  filter(cbudget == tbudgetdvgm)

tempmeandata <- temppkdata %>%
  group_by(variable) %>%
  summarize(value = mean(value))

# TODO: This is currently wrong, as the points are not lining
# up with the stacked bar. Fix in post for now.
tempmeandata %>% 
# temppkdata %>% 
  filter(!variable %in% c("Emi|CO2|Cum")) %>%
  # filter(scenario == "C_ESM2025v05-LPJml-SSP2-PkBudg620-rem-5") %>%
  # filter(lsm == "CABLEPOP") %>%
  # ggplot(aes(x = scenario, y = value, fill = variable)) +
  ggplot(aes(x = 1, y = value, fill = variable)) +
  geom_bar(position="stack", stat="identity") +
  geom_point(
    data = filter(
      temppkdata, 
      variable != "Emi|CO2|+|Energy and Industrial Processes|Cum"
      ), 
    size = 2,
    aes(x = 2, color = lsm)  
    ) +
  scale_color_manual(values = modelcolors) + 
  labs(
    y = "Peak Cumulative CO2 emissions since 2020 [GtCO2]",
    color = "DVGM"
  ) +
  theme_classic() +
  theme(
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 16)
  )
ggsave("illus_stackbar.svg", width = 6, height = 8)
"C_ESM2025v05-LPJml-SSP2-PkBudg840-rem-5"
"Emi|CO2|Cumulated|Energy and Industrial Processes (Mt CO2)"
"Emi|CO2|Cumulated|Land-Use Change (Mt CO2)"

# Split LUC with regrowth ==============
lucmif <-
  bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable %in% c(
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Deforestation",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Other land conversion",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Peatland",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Regrowth",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Residual",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Soil",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Timber",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Wood Harvest"
  )) %>%
  filter(period == 2050) %>%
  mutate(grosspositive = ifelse(value >= 0, "Gross-positive LUC emission categories", "Gross-negative LUC emission categories")) %>%
  group_by(across(-c("variable", "value"))) %>%
  summarize(value = sum(value)) %>%
  ungroup %>%
  left_join(tbudgetinfo) %>%
  filter(cbudget == tbudgetdvgm) %>%
  mutate(variable = grosspositive)

p1 <- bind_rows(filter(tbudgetmif,model!="AR6"),lucmif) %>%
  select(variable, lsm, value) %>%
  pivot_wider(names_from = variable, values_from = value) %>% 
  ggplot(aes(y = `Carbon budget to 1.7C 50th perc.`, x = `Gross-positive LUC emission categories`, color = lsm)) +
  geom_point(size = 2) +
  scale_color_manual(values = modelcolors)
  
p2 <- bind_rows(filter(tbudgetmif,model!="AR6"),lucmif) %>%
  select(variable, lsm, value) %>%
  pivot_wider(names_from = variable, values_from = value) %>% 
  ggplot(aes(y = `Carbon budget to 1.7C 50th perc.`, x = `Gross-negative LUC emission categories`, color = lsm)) +
  geom_point(size = 2) +
  scale_color_manual(values = modelcolors)


cowplot::plot_grid(p1,p2)


# ====================================================================
# AR6 ensemble plot to check if using budgets is ok
mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  filter(caltype == "AR6 Ensemble") %>%
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(500, 720, by = 20))

# ====================================================================
# Checking airborne fraction calculation
mixbigmif %>%
  filter(variable %in% c(
    "Harmonized|Emissions|CO2|Cum",
    "Atmospheric Concentrations|CO2|EqEm2020|q50",
    "Airborne Fraction|Since2020|q50"
  )) %>%
  mutate(value = ifelse(
    variable == "Airborne Fraction|Since2020|q50",
    ifelse(value < (-0.5), NA, value) * 100,
    value * 1e-3
  )) %>%
  filter(period <= 2100) %>%
  filter(policy == "PkBudg600") %>%
  filter(lsm == "LPJml") %>%
  filter(period == 2040) %>%
  select(variable, model, value) %>%
  print(n = 1000)
ggplot(aes(x = period, y = value, color = model)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y", ncol = 1)

# ====================================================================
# REMIND-MAgPIE only plots
# ====================================================================

# ===================================================================
# Summary plots

# Basic summary plots
usebudget <- musebudget
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      "Resources|Land Cover|+|Forest",
      "Emi|CO2|+|Energy|Cum",
      "Emi|CO2|+|Land-Use Change|Cum",
      "Price|Carbon"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget == usebudget) %>%
  ggplot(aes(x = lsm, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "",
    color = "C densities from DVGM:"
  )

# Summary vs. LUC emissions

xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(cbudget == usebudget, region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest Area in 2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2050" ~ "Cum. Gross FFI CO2 emissions in 2050 [GtCO2]",
    variable == "Price|Carbon in 2050" ~ "Carbon Price in 2050 [$/tCO2]",
    variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2050" ~ "Total cum. CDR in 2050 [$/tCO2]",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  # filter(str_detect(policy, "PkBudg")) %>%
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()
ggsave(paste0("summary_Xlucemi2050_", usebudget, ".png"), width = 10, height = 7)
ggsave(paste0("summary_Xlucemi2050_", usebudget, ".svg"), width = 10, height = 7)


mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  filter(variable %in% c(
    "Harmonized|Emissions|CO2|Cum",
    "Surface Air Temperature Change|q67",
    "Effective Radiative Forcing|q67",
    "Effective Radiative Forcing|CH4|q67",
    "Effective Radiative Forcing|N2O|q67",
    "Effective Radiative Forcing|CO2|q67"
  ), model %in% c("AR6","REMIND-MAgPIE","REMIND")) %>%
  left_join(nzmif) %>%
  filter(period == nzyearharm) %>%
  mutate(variable = paste0(variable, " at net-zero")) %>%
  left_join(xmif) %>% #select(variable) %>% unique
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()

mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Harmonized|Emissions|CO2|Cum in 2050" ~ "Cum. CO2 emissions in 2050 [$/tCO2]",
    variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  # filter(str_detect(policy, "PkBudg")) %>%
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()
ggsave(paste0("summaryclim_Xlucemi2050_", usebudget, ".png"), width = 10, height = 7)

# CDR Summary plots
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      # "Emi|CO2|CDR",
      # "Emi|CO2|CDR|+|BECCS",
      # "Emi|CO2|CDR|+|DACCS",
      # # "Emi|CO2|CDR|+|EW",
      # "Emi|CO2|CDR|+|Land-Use Change"
      # # "Price|Carbon"
      "Emi|CO2|Cumulated|CDR",
      "Emi|CO2|Cumulated|CDR|BECCS",
      # "Emi|CO2|Cumulated|CDR|BECCS|Demand Side",
      # "Emi|CO2|Cumulated|CDR|BECCS|Pe2Se",
      "Emi|CO2|Cumulated|CDR|DACCS",
      # "Emi|CO2|Cumulated|CDR|EW",
      "Emi|CO2|Cumulated|CDR|Land-Use Change"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget == usebudget) %>%
  ggplot(aes(x = lsm, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "fixed", ncol = 2) +
  # facet_wrap(~variable+period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "",
    color = "C densities from DVGM:"
  )


# Temp vs. budgets
useyear <- 2100
bigmif %>%
  filter(
    region == "GLO",
    variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    # variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("GSAT ", useyear, " 67th perc. [K]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 20))



# Prices vs. budgets
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Price|Carbon"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  group_by(scenario, cbudget, lsm) %>%
  summarise(peakprice = max(value, na.rm = T)) %>%
  ungroup() %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = peakprice, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = "Carbon Price at net-zero [USD2017/tCO2]",
    color = "C densities from DVGM:"
  ) +
  scale_y_continuous(
    breaks = seq(0, 3000, by = 100),
    minor_breaks = seq(0, 3000, by = 25)
  ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXprice.png")
ggsave("budgetXprice.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  # filter(lsm == "LPJml") %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  # theme(legend.position = "bottom", legend.orientation = "horizontal") +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXlucemi.png")
ggsave("budgetXlucemi.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    # variable == "Emi|CO2|+|Energy|Cum"
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  # theme(legend.position = "bottom", legend.orientation = "horizontal") +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative gross energy and industry CO2 emissions\n2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXeneemi.png")
ggsave("budgetXeneemi.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(region == "World") %>%
  calc_addVariable(
    emiffi = "`Emi|CO2|+|Land-Use Change|Cum` +
            `Emi|CO2|+|Energy|Cum` +
    `Emi|CO2|+|Industrial Processes|Cum` +
    `Emi|CO2|+|Waste|Cum` +
    `Emi|CO2|+|non-ES CDR|Cum`"
  ) %>%
  filter(variable == "emiffi") %>%
  # filter(
  #     region == "World",
  #     # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
  #     variable == "Emi|CO2|+|Land-Use Change|Cum"
  # ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(cbudget >= 600) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXffiemi.png")
ggsave("budgetXffiemi.svg")



# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Resources|Land Cover|+|Forest"
  ) %>%
  # mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  # group_by(cbudget) %>% summarise(minval = min(value), maxval = max(value)) %>% mutate(diff = maxval-minval)
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Global forest area in ", useyear, " [Mha]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXforest.png")
ggsave("budgetXforest.svg")


# CDR vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Emi|CO2|CDR"
  ) %>%
  mutate(value = value * 1e3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(cbudget >= 600) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("CDR deployment in", useyear, " [GtCO2/yr]"),
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(600, 720, by = 20))

# ===================================================================
# CDR isoline plots
# ===================================================================

useyears <- c(2050, 2100)
usebudget <- musebudget

xvarname <- "Emi|CO2|Cumulated|CDR|Land-Use Change"
yvarname <- "Emi|CO2|Cumulated|CDR|BECCS"
zvarname <- "Emi|CO2|Cumulated|CDR"
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable %in% c(xvarname, yvarname, zvarname)
  ) %>%
  mutate(value = value * 1e-3 * -1) %>% # MtCO2 to GtCO2 and make positive
  filter(str_detect(policy, "PkBudg")) %>%
  filter(cbudget == usebudget) %>%
  mutate(variable = case_when(
    variable == xvarname ~ "xvar",
    variable == yvarname ~ "yvar",
    variable == zvarname ~ "zvar"
  )) %>%
  select(scenario, period, variable, value, cbudget, lsm) %>%
  filter(period %in% useyears) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  ggplot(aes(x = xvar, y = yvar, color = lsm)) +
  geom_textabline(
    aes(intercept = alpha, slope = beta, label = alpha),
    color = "grey70",
    data = data.frame(alpha = seq(0, 1000, 20), beta = -1)
  ) +
  geom_abline(aes(intercept = zvar, slope = -1, color = lsm)) +
  # geom_abline(intercept = seq(0,1000,10), slope = -1, color = "grey70") +
  geom_point(size = 3) +
  theme_bw() +
  labs(
    x = "Cumulative LUC CDR since 2020 [GtCO2]",
    y = "Cumulative BECCS CDR since 2020 [GtCO2]",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  facet_wrap(~period, scales = "free") +
  scale_color_manual(values = modelcolors)
# theme(legend.position = "bottom", legend.orientation = "horizontal") +
# scale_x_continuous(breaks = seq(600, 720, by = 20))
ggsave("cdr_isolines.png", height = 4, width = 10)
ggsave("cdr_isolines.svg", height = 4, width = 10)


# ===================================================================
# Stuff for Sirisha
# ===================================================================
usebudget <- 720
bigmif %>%
  filter(cbudget == usebudget) %>%
  write.mif("for_sirisha_20may.mif")


bigmif %>%
  filter(cbudget == usebudget) %>%
  filter(variable %in% c(
    "Emi|CO2|CDR|+|BECCS",
    "Emi|CO2|CDR|+|DACCS",
    "Emi|CO2|CDR|+|EW",
    "Emi|CO2|CDR|+|Land-Use Change",
    "Emi|CO2|CDR|+|Materials",
    "Emi|CO2|CDR|+|OAE",
    "Emi|CO2|CDR|+|Synthetic Fuels CCS"
  ))

bigmif %>%
  filter(cbudget == usebudget, region == "World") %>%
  filter(variable %in% c(
    "Emissions|CO2|Land RAW|Land-use Change|+|Forest degradation",
    "Emissions|CO2|Land RAW|Land-use Change|+|Other land conversion",
    "Emissions|CO2|Land RAW|Land-use Change|+|Peatland",
    "Emissions|CO2|Land RAW|Land-use Change|+|Regrowth",
    "Emissions|CO2|Land RAW|Land-use Change|+|Residual",
    "Emissions|CO2|Land RAW|Land-use Change|+|Soil",
    "Emissions|CO2|Land RAW|Land-use Change|+|Timber",
    "Emissions|CO2|Land RAW|Land-use Change|+|Wood Harvest"
  )) %>%
  mutate(variable = str_replace(variable, "Emissions\\|CO2\\|Land RAW\\|Land-use Change\\|\\+\\|", "")) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y")

unique(bigmif$variable)

bigmif %>%
  filter(cbudget == usebudget, region == "World") %>%
  filter(variable %in% c(
    "Resources|Land Cover|+|Forest"
  )) %>%
  mutate(variable = str_replace(variable, "Emissions\\|CO2\\|Land RAW\\|Land-use Change\\|\\+\\|", "")) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  facet_wrap(~variable, scales = "free_y")

bigmif %>%
  filter(cbudget == usebudget, region == "World") %>%
  filter(variable %in% c(
    "Resources|Land Cover|+|Forest"
  )) %>%
  filter(lsm == "LPJml") %>%
  arrange(period) %>%
  mutate(delta = value - lag(value))
options(width = 120)

# ===================================================================
# Deriving TCRE from AR6 calibration
# ===================================================================
tmpmif <- bigmif %>%
  filter(
    region == "World",
    variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    # variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(cbudget >= 600)

tmpmif %>%
  filter(cbudget == 600) %>%
  rename(val600 = value) %>%
  select(-cbudget, -scenario) %>%
  left_join(tmpmif, .) %>%
  mutate(
    dt = value - val600,
    dc = cbudget - 600,
    tcre = 1000 * dt / dc
  ) %>%
  ggplot(aes(x = cbudget, y = tcre, color = lsm)) +
  geom_point()


# ===================================================================
# Regional
# ===================================================================
usebudget <- musebudget
# CDR Summary plots
bigmif %>%
  filter(
    !(region %in% c("GLO", "World")),
    variable %in% c(
      "Emi|CO2|Cumulated|CDR|Land-Use Change"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget == usebudget) %>%
  ggplot(aes(
    x = region, y = value,
    color = lsm, group = lsm
  )) +
  geom_point(size = 3) +
  geom_line() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "fixed", ncol = 2) +
  # facet_wrap(~variable+period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "",
    color = "C densities from DVGM:"
  )

# ===================================================================
# Investigating differences with standard assessment
# ===================================================================

mixbigmif %>%
  filter(
    (region %in% c("GLO", "World")),
    variable %in% c(
      "Emi|CO2|Cum",
      "Harmonized|Emissions|CO2|Cum",
      "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile",
      "Surface Air Temperature Change|q67"
    ),
    # lsm %in% c("CABLEPOP", "LPJwsl"),
    lsm %in% c("LPJml"),
    # cbudget %in% c(900, 920, 940, 960, 980)
    between(cbudget, 800, 900)
  ) %>%
  filter(model %in% c("AR6","REMIND-MAgPIE")) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  scale_color_manual(values = modelcolors) +
  facet_grid(variable ~ cbudget, scales = "free") +
  theme_bw()

# ===================================================================
# Scratch
# ===================================================================

mixbigmif %>%
  filter(
    (region %in% c("GLO", "World")),
    variable %in% c(
      "Harmonized|Emissions|CO2",
      "Harmonized|Emissions|CO2|MAGICC AFOLU",
      "Harmonized|Emissions|CO2|MAGICC Fossil and Industrial",
      "Harmonized|Emissions|CO2|Cum",
      "Price|Carbon"
    ),
    lsm %in% c("CABLEPOP", "LPJwsl"),
    cbudget %in% c(900, 920, 940, 960, 980)
  ) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  scale_color_manual(values = modelcolors) +
  facet_grid(variable ~ cbudget, scales = "free") +
  theme_bw()

bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    # scenario %in% c(
    #   "C_ESM2025v05-LPJml-SSP2-PkBudg840-rem-5",
    #   "C_ESM2025v05-ORCHIDEE-SSP2-PkBudg840-rem-5"
    # ),
    cbudget == musebudget,
    variable %in% c(
      # "FE|Transport|Fuels|Share",
      # "FE|Transport|Electricity|Share",
      "PE|Fossil",
      # "PE|+|Coal",
      "FE|Electricity|Share",
      "PE",
      "Emi|CO2"
  )) %>%
  calc_addVariable("PE share of fossils [%]" = "100*`PE|Fossil`/`PE`") %>%
  filter(!(variable %in% c(
    "PE",
    "PE|Fossil"
  ))) %>%
  mutate(variable = case_when(
    # variable == "FE|Transport|Fuels|Share" ~ "Share (%)",
    # variable == "FE|Transport|Electricity|Share" ~ "Electrification share of transport [%]",
    # variable == "PE|Fossil" ~ "Primary energy from fossil fuels [EJ/yr]",
    # variable == "PE|+|Coal" ~ "Primary energy from coal [EJ/yr]",
    variable == "Emi|CO2" ~ "Total CO2 emissions [Mt/yr]",
    variable == "FE|Electricity|Share" ~ "Electricity share of final energy [%]",
    TRUE ~ variable
  )) %>% #filter(period == 2070) %>% arrange(variable) %>% print(n=1000)
  filter(between(period, 2025, 2070)) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "Share, EJ/yr or MtCO2/yr",
    color = "C densities from DVGM:"
  ) +
  theme_bw() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  facet_wrap(~variable, scales = "free_y")
ggsave("transition_indicators.png", width = 10, height = 5)
# ggsave("transition_indicators.png", width = 10, height = 7)



nzmifraw %>%
  left_join(sceninfo) %>%
  filter(cbudget == musebudget)

dum <- mixbigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      "Emissions|CO2|Land|Cumulative|+|Land-use Change",
      "Emissions|CO2|Land|Cumulative|Land-use Change|++|Above Ground Carbon",
      "Emissions|CO2|Land|Cumulative|Land-use Change|++|Below Ground Carbon",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Deforestation",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Other land conversion",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Peatland",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Regrowth",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Residual",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Soil",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Timber",
      "Emissions|CO2|Land|Cumulative|Land-use Change|+|Wood Harvest"
    )) %>% #select(scenario) %>% unique
  filter(scenario == "C_ESM2025v05-CABLEPOP-SSP2-PkBudg720-rem-5") %>%
  filter(period <= 2060) #%>%
dum %>%
  filter(variable != "Emissions|CO2|Land|Cumulative|+|Land-use Change") %>%
  # ggplot(aes(x = period, y = value, color = variable)) +
  # geom_line() +
  ggplot(aes(x = period, y = value, fill = variable)) +
  geom_area() +
  geom_line(data = filter(
    dum, variable == "Emissions|CO2|Land|Cumulative|+|Land-use Change"),
    aes(x = period, y = value), linewidth = 2) +
    geom_hline(yintercept = 0)


# mixbigmif %>%
#   filter(
#     region %in% c("GLO", "World"),
#     str_detect(variable, "Surface Air Temperature Change|")
#     )
