require(tidyverse)
require(quitte)
require(magclass)
require(lucode2)
require(geomtextpath)
require(ggpubr)
require(ggpp)
require(GGally)
require(mip)
options(width = 140)

# Model colors, may be renamed or filtered  in preprocessing
source("colors_models_v1.R")
# REMIND-MAgPIE variables to keep from the MIF
# extractvarsrem and extractvarsmag variables come from here
source("extractvars_v1.R")
source("functions_v1.R")

# Master setup for choosing scenarios in plots
mlowbudget <- 540
mhigbudget <- 920
musebudget <- 560 # Closest to 1.7K50 in most models in AR6 (560-580)
# musebudget <- 840 # Closest to 2K67 in most models in AR6 (800-880)

# Temporary, generated by postprocess_gang_v5 script
# climfname <- "qlclim_gangv03sub600_E25v05p1.rds"
# climfname <- "qlclimadj_gangv03sub600_E25v05p1.rds"
climfname <- "qlclimadj_gangv04sub600_E25v05p1.rds"

# Input global mean stocks (land area weighted), from compare_franken.R  
allglostocksfname <- "table_globalmean_stocks.csv"

# Historical TRENDY fluxes, among other cablibration data
histfluxfname <- "fulloutput_20models_CandN_v9.csv"

# Harmonized emission file
harmfname <- "ESM2025v05p1_full_harmonized_clean.csv"

# mifpaths <- Sys.glob("output/*-rem-5/REMIND_generic*.mif")
mifpaths <- Sys.glob("clusterdown_v05p1/REMIND_generic*.mif")
mifpaths <- mifpaths[str_detect(mifpaths, "withoutPlus", negate = TRUE)]

# Rerun/caching toggles for the preprocessing step (preprocess_v2.R)
# rerun_bigmif <- TRUE
rerun_bigmif <- FALSE
rerun_mixbigmif <- FALSE
# rerun_bigmif <- FALSE
# rerun_mixbigmif <- FALSE

# ====================================================================
# Model renaming and filtering configuration
# This mapping is applied as the last step in preprocessing to:
#   1. Rename models in bigmif and mixbigmif data
#   2. Filter out models from the data (0 = exclude, 1 = include)
#   3. Update the modelcolors mapping accordingly
# ====================================================================
rename_models <- list(
  # Vector of old_name = new_name for renaming
  rename = c("LPJml" = "LPJmL"),

  # Named vector with 1 = include model, 0 = exclude model
  # Leave empty (numeric()) to include all models
  include = c("lpxqs" = 0)
)

# ====================================================================
# Preprocessing: reads and caches the MIF databases using the config
# set above. Produces bigmif, mixbigmif, sceninfo, allglostocks,
# stockmodels and histfluxmif for the plots below.
# ====================================================================
source("preprocess_v2.R")



# ====================================================================
# Mixed MAGICC and REMIND-MAgPIE only plots
# ====================================================================
usebudget <- musebudget
useyear <- 2050

# Figure B5: DVGM vs. ensemble uncertainty ===========================
mixbigmif %>%
  filter(variable %in% c(
    "Surface Air Temperature Change|q33",
    "Surface Air Temperature Change|q50",
    "Surface Air Temperature Change|q67",
    "Surface Air Temperature Change|q90",
    "Surface Air Temperature Change|q10"
  )) %>%
  filter(cbudget == usebudget, period %in% c(2050,2100)) %>%
  mutate(model = ifelse(model != "AR6", "AR6 ensemble +\nLand C cycle\ncalibrated to DVGM", "Pure AR6\nensemble")) %>%
  mutate(model = factor(model, levels = c("Pure AR6\nensemble", "AR6 ensemble +\nLand C cycle\ncalibrated to DVGM"))) %>%
  mutate(variable = str_remove(variable, "Surface Air Temperature Change\\|")) %>%
  # group_by(variable,model,period) %>%
  # summarise(min = min(value), max = max(value), mean = mean(value))
  ggplot(aes(x = model, y = value, fill = variable)) +
  # geom_jitter(size = 0.5) +
  geom_boxplot() +
  geom_text(
    data = tibble(period = c(2050, 2100), label = c("a", "b")),
    aes(x = -Inf, y = Inf, label = label),
    inherit.aes = FALSE,
    hjust = -0.5,
    vjust = 1.5
  ) +
  facet_wrap(~period, scales = "free") +
    labs(
    x = "",
    y = paste0("GSAT [K]"),
    fill = "Quantile from 600\nclimate parametrizations:"
  ) +
  theme_bw() +
  theme(
    legend.position = "bottom", 
    legend.direction = "horizontal", 
    legend.title.position = "top",
    legend.title = element_text(hjust = 0.5),
    legend.justification = "center"
    ) 
ggsave(paste0("figB5_tempvsquantiles", "_", usebudget, "_", "bothyears", ".png"), width = 6, height = 5)
ggsave(paste0("figB5_tempvsquantiles", "_", usebudget, "_", "bothyears", ".svg"), width = 6, height = 5)

# ====================================================================
# Test picking temperature target scenario
# ====================================================================
# Net-zero year from harmonized emissions
nzmif <- mixbigmif %>%
  filter(variable == "Harmonized|Emissions|CO2") %>%
  filter(!is.na(cbudget)) %>%
  group_by(scenario) %>%
  select(scenario, period, value) %>%
  mutate(value = abs(value)) %>%
  filter(value == min(value)) %>%
  ungroup() %>%
  rename(nzyearharm = period) %>%
  select(scenario, nzyearharm)

# Net-zero year from raw emissions
nzmifraw <- bigmif %>%
  filter(region == "GLO") %>%
  filter(variable == "Emi|CO2") %>%
  filter(!is.na(cbudget)) %>%
  group_by(scenario) %>%
  select(scenario, period, value) %>%
  mutate(value = abs(value)) %>%
  filter(value == min(value)) %>%
  ungroup() %>%
  rename(nzyearraw = period) %>%
  select(scenario, nzyearraw)

# Figure B2: Peak GSAT vs. Carbon Budget (AR6 ensemble only) ===========================
p1 <- mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, variable, value, cbudget, lsm, caltype) %>%
  group_by(scenario, variable, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  geom_text(
    data = tibble(
      variable = c("Surface Air Temperature Change|q50", "Surface Air Temperature Change|q67"),
      label = c("a", "c")
    ),
    aes(x = -Inf, y = Inf, label = label),
    inherit.aes = FALSE,
    hjust = -0.5,
    vjust = 1.5
  ) +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT (50th or 67th percentile) [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
print(p1)
ggsave("temp_budgets_AR6_peak.png", width = 7, height = 8)
ggsave("temp_budgets_AR6_peak.svg", width = 7, height = 8)


p2 <- mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(model,scenario, period, variable, value, cbudget, lsm, caltype) %>%
  # group_by(scenario, caltype) %>%
  # filter(value == max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == 2100) %>%
  # select(model) %>% unique
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  geom_text(
    data = tibble(
      variable = c("Surface Air Temperature Change|q50", "Surface Air Temperature Change|q67"),
      label = c("b", "d")
    ),
    aes(x = -Inf, y = Inf, label = label),
    inherit.aes = FALSE,
    hjust = -0.5,
    vjust = 1.5
  ) +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("2100 GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
print(p2)
ggsave("temp_budgets_AR6_EoC.png", width = 7, height = 8)
ggsave("temp_budgets_AR6_EoC.svg", width = 7, height = 8)

leg <- get_legend(p1)
pcomb <- cowplot::plot_grid(
  p1 + theme(legend.position = "none"),
  p2 + theme(legend.position = "none")
)
cowplot::plot_grid(pcomb, leg, ncol = 2, rel_widths = c(1, 0.3)) +
  theme(plot.background = element_rect(fill = "white", color = NA))
ggsave("figb2_temp_budgets_AR6_peak_and_EoC.png", width = 10, height = 8)
ggsave("figb2_temp_budgets_AR6_peak_and_EoC.svg", width = 10, height = 8)


# Figure B6: Peak GSAT vs. Carbon Budget (density and budget effects) ==========================
mixbigmif %>%
  filter(
    region == "World",
    variable %in% c(
      # "Surface Air Temperature Change|q67",
      "Surface Air Temperature Change|q50"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated to DVGM (incl. Budget effects)", "AR6 Ensemble")) %>%
  select(scenario, period, variable, value, cbudget, lsm, caltype) %>%
  group_by(scenario, variable, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  # filter(caltype == "AR6 Ensemble") %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  geom_hline(yintercept = 1.7, lty = "solid", color = "grey30") +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT (50th or 67th percentile) [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  facet_wrap(~variable, ncol = 1, scales = "free") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("figB6_temp_budgets_both_just50_peak.png", width = 8, height = 5)
ggsave("figB6_temp_budgets_both_just50_peak.svg", width = 8, height = 5)

# KEY: Target budget estimation ===========================

ttarget <- 1.7
tbudgetinfo <- mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q50"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "tbudgetdvgm", "tbudgetar6")) %>% #View
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>% #View
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  select(-period) %>%
  # rename(period = cbudget) %>%
  # interpolate_missing_periods(seq(400, 800, 1), expand.values = F) %>%
  group_by(caltype, lsm) %>%
  # mutate(diff = (abs(value - ttarget))) %>%
  mutate(diff = (-1 * (value - ttarget))) %>%
  mutate(diff = ifelse(diff < 0, NA, diff)) %>% #View
  filter(diff == min(diff, na.rm = T)) %>%
  select(caltype, lsm, cbudget) %>%
  pivot_wider(names_from = caltype, values_from = cbudget)
tbudgetinfo

# Choose a single budget for the AR6 version, they are really close
tbudgetinfo <- tbudgetinfo %>%
  mutate(tbudgetar6 = median(tbudgetinfo$tbudgetar6))

tbudgetmif <- tbudgetinfo %>%
  pivot_longer(-lsm, names_to = "variable") %>%
  mutate(model = ifelse(variable == "tbudgetar6", "AR6", lsm)) %>%
  mutate(variable = "Carbon budget to 1.7C 50th perc.")

mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q50"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>% 
  # filter(lsm == model | model == "AR6") %>%
  # mutate(caltype = ifelse(model != "AR6", "tbudgetdvgm", "tbudgetar6")) %>% #View
  select(scenario, model, period, value, cbudget, lsm) %>% 
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, model) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>% #View
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  select(-period) %>%
  # rename(period = cbudget) %>%
  # interpolate_missing_periods(seq(400, 800, 1), expand.values = F) %>%
  group_by(model, lsm) %>%
  # mutate(diff = (abs(value - ttarget))) %>%
  mutate(diff = (-1 * (value - ttarget))) %>%
  mutate(diff = ifelse(diff < 0, NA, diff)) %>% #View
  filter(diff == min(diff, na.rm = T)) %>%
  select(model, lsm, cbudget) %>%
  pivot_wider(names_from = model, values_from = cbudget)



mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  group_by(caltype, lsm) %>%
  summarise(in_range = any(value >= ttarget)) %>%
  pivot_wider(names_from = caltype, values_from = in_range)

# ====================================================================
# Summary plots with target budget comparison =================
# ====================================================================
# MAIN Figure 2: Summary (main) with same variables as previous section ==========================
xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

varorder <- c(
  "Carbon budget\nto 1.7°C 50th perc.[GtCO2]",
  "Forest area change\n2020-2050 [Mha]",
  "Total cum. CDR\nin 2050 [$/tCO2]",
  "Cum. Gross FFI CO2 emi.\nin 2050 [GtCO2]",
  "Airborne Fraction of\nemis. 2020-2050 [%]"
)

combmif <- mixbigmif %>%
  filter(
    # cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    variable == "Airborne Fraction|Since2020|q50" ~ value * 100, # fraction to percent
    TRUE ~ value
  )) %>%
  rebase_to_period(2020, variables = c("Resources|Land Cover|+|Forest")) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest area change\n2020-2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest Area in 2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2050" ~ "Cum. Gross FFI CO2 emi.\nin 2050 [GtCO2]",
    # variable == "Price|Carbon in 2050" ~ "Carbon Price in 2050 [$/tCO2]",
    # variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2050" ~ "Total cum. CDR\nin 2050 [$/tCO2]",
    variable == "Airborne Fraction|Since2020|q50 in 2050" ~ "Airborne Fraction of\nemis. 2020-2050 [%]",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  mutate(variable = fct_relabel(variable, ~ str_replace(.x, " in 20", "\n20"))) %>% # Add line breaks for years in variable names
  mutate(variable = fct_relabel(variable, ~ str_replace(.x, " to 1.7C", "\nto 1.7°C"))) %>%
  # rebase_to_period(2020, variables = c("Forest area change 2020-2050 [Mha]"), only.new = TRUE) %>% View
  filter_tbudget(tbudgetinfo) %>%
  left_join(tbudgetinfo) #%>% #View

# # bind_rows(combmifar6, combmifdvgm)%>% #View#select(lsm) %>% unique
# mixbigmif %>% filter(
#   variable == "Airborne Fraction|Since2020|q50",
#   period == 2050
#   ) -> inmif
# combmif %>% filter(variable == "Airborne Fraction since 2020 [%]") %>% View
# tbudgetinfomif = tbudgetinfo
# mixbigmif %>% select(lsm) %>% unique %>% print(n=1000)

dum <- combmif %>%
  bind_rows(
    tbudgetmif %>%
      mutate(model = ifelse(model == "AR6","Density effect", "Density + Budget effects")) %>%
      # mutate(variable = fct_relabel(variable, ~ str_replace(.x, " to 1.7C", "\nto 1.7°C"))) %>%
      mutate(variable = fct_relabel(variable, ~ paste0(str_replace(.x, " to 1.7C", "\nto 1.7°C"), "[GtCO2]"))) %>%      
      left_join(rename(xmif, value = cbudget))
    ) %>%
    mutate(variable = factor(variable, levels = varorder)) %>%
    mutate(model = fct_relevel(model, "Density effect", "Density + Budget effects"))

dum %>% select(variable) %>% unique %>% print(n=1000)
dum %>% write.csv("summary_tbudget_1p7K50_dvgm.csv", row.names = F)    
# facet row order, given as the raw variable names in dum
x_range <- diff(range(dum$xvar, na.rm = TRUE))
facet_ranges <- dum %>%
  group_by(variable, model) %>%
  summarise(
    min_value = min(value, na.rm = TRUE),
    max_value = max(value, na.rm = TRUE),
    range_value = max_value - min_value,
    xbar = max(xvar, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    xbar = xbar + 0.05 * x_range,
    xtext = xbar + 0.04 * x_range,
    ymid = (min_value + max_value) / 2,
    panel_label = letters[(seq_len(n()))]
  )

dum %>%
  ggplot(aes(x = xvar, y = value, color = lsm, shape = model)) +
  geom_point(size = 3) +
  geom_text(
    data = facet_ranges,
    aes(x = -Inf, y = Inf, label = panel_label),
    inherit.aes = FALSE,
    hjust = -0.5,
    vjust = 1.5,
    color = "black"
  ) +
  geom_errorbar(
    data = facet_ranges,
    aes(x = xbar, ymin = min_value, ymax = max_value),
    inherit.aes = FALSE,
    width = 0.03 * x_range,
    color = "black"
  ) +
  geom_text(
    data = facet_ranges,
    aes(x = xtext, y = ymid, label = sprintf("%.0f", range_value)),
    inherit.aes = FALSE,
    angle = -90,
    hjust = 0.5,
    vjust = 0.5,
    color = "black"
  ) +
  facet_grid(
    variable ~ model, 
    scales = "free_y",
    switch = "y"
    ) +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  theme(
    strip.placement = "outside",
    strip.background = element_blank(),
    strip.text.y.left = element_text(angle = 90)
  ) +
  labs(
    x = "Cost-effective cum. LUC emissions since 2020 [GtCO2]",
    y = "",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
  )
ggsave("fig2_summary_tbudget_1p7K50_dvgm.png", width = 9, height = 9)
ggsave("fig2_summary_tbudget_1p7K50_dvgm.svg", width = 9, height = 9)

# Summary statistics for the figure
dum %>% 
  group_by(variable, model) %>%
  summarise(min = min(value), max = max(value), dif = max-min,mean = mean(value), dpc = 100*dif/mean)

dum %>% 
  filter(variable == "Forest area change\n2020-2050 [Mha]") %>%
  group_by(variable, model) %>%
  mutate(variable = xvarname) %>%
  summarise(min = min(xvar), max = max(xvar), dif = max-min,mean = mean(xvar), dpc = 100*dif/mean)

dum %>%
  filter(variable == "Forest area change\n2020-2050 [Mha]") %>%
  mutate(xvar = -xvar) %>%
  mutate(value = value/xvar) %>%
  ggplot(aes(x = xvar, y = value, color = lsm, shape = model)) +
  geom_point(size = 3) +
  geom_line(aes(group = lsm)) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC CDR since 2020 [GtCO2]",
    y = "Cum. LUC CDR per forest area change 2020-2050 [1000tCO2/ha]",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
    ) +
    theme_bw()
ggsave("luc_per_forest.png", width = 8, height = 6)


# Figure B10 : Summary for 2100 ==========================
xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2100) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

# mixbigmif %>%
#   filter(region %in% c("GLO", "World")) %>%
#   filter(variable == "Price|Carbon") %>%
#   filter(period == 2100) %>%
#   View

# C_ESM2025v05-LPJwsl-SSP2-PkBudg540-rem-5
varorder <- c(
  "Carbon budget\nto 1.7°C 50th perc.[GtCO2]",
  "Forest area change\n2020-2100 [Mha]",
  "Total cum. CDR\nin 2100 [$/tCO2]",
  "Cum. Gross FFI CO2 emi.\nin 2100 [GtCO2]",
  "Airborne Fraction of\nemis. 2020-2100 [%]"
)

combmif <- mixbigmif %>%
  filter(
    # cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2100, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    variable == "Airborne Fraction|Since2020|q50" ~ value * 100, # fraction to percent
    TRUE ~ value
  )) %>%
  rebase_to_period(2020, variables = c("Resources|Land Cover|+|Forest")) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest area change\n2020-2100 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2100" ~ "Cum. Gross FFI CO2 emi.\nin 2100 [GtCO2]",
    # variable == "Price|Carbon in 2100" ~ "Carbon Price in 2100 [$/tCO2]",
    # variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2100" ~ "Total cum. CDR\nin 2100 [$/tCO2]",
    variable == "Airborne Fraction|Since2020|q50 in 2100" ~ "Airborne Fraction of\nemis. 2020-2100 [%]",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  mutate(variable = fct_relabel(variable, ~ str_replace(.x, " in 20", "\n20"))) %>% # Add line breaks for years in variable names
  mutate(variable = fct_relabel(variable, ~ str_replace(.x, " to 1.7C", "\nto 1.7°C"))) %>%
  # rebase_to_period(2020, variables = c("Forest area change 2020-2100 [Mha]"), only.new = TRUE) %>% View
  filter_tbudget(tbudgetinfo) %>%
  left_join(tbudgetinfo) #%>% #View

# # bind_rows(combmifar6, combmifdvgm)%>% #View#select(lsm) %>% unique
# mixbigmif %>% filter(
#   variable == "Airborne Fraction|Since2020|q50",
#   period == 2100
#   ) -> inmif
# combmif %>% filter(variable == "Airborne Fraction since 2020 [%]") %>% View
# tbudgetinfomif = tbudgetinfo
# mixbigmif %>% select(lsm) %>% unique %>% print(n=1000)

dum <- combmif %>%
  bind_rows(
    tbudgetmif %>%
      mutate(model = ifelse(model == "AR6","Density effect", "Density + Budget effects")) %>%
      # mutate(variable = fct_relabel(variable, ~ str_replace(.x, " to 1.7C", "\nto 1.7°C"))) %>%
      mutate(variable = fct_relabel(variable, ~ paste0(str_replace(.x, " to 1.7C", "\nto 1.7°C"), "[GtCO2]"))) %>%      
      left_join(rename(xmif, value = cbudget))
    ) %>%
    mutate(variable = factor(variable, levels = varorder)) %>%
    mutate(model = fct_relevel(model, "Density effect", "Density + Budget effects"))

dum %>% select(variable) %>% unique %>% print(n=1000)
dum %>% write.csv("summary_tbudget_1p7K50_dvgm.csv", row.names = F)    
# facet row order, given as the raw variable names in dum
x_range <- diff(range(dum$xvar, na.rm = TRUE))
facet_ranges <- dum %>%
  group_by(variable, model) %>%
  summarise(
    min_value = min(value, na.rm = TRUE),
    max_value = max(value, na.rm = TRUE),
    range_value = max_value - min_value,
    xbar = max(xvar, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    xbar = xbar + 0.05 * x_range,
    xtext = xbar + 0.04 * x_range,
    ymid = (min_value + max_value) / 2,
    panel_label = letters[(seq_len(n()))]
  )

dum %>%
  ggplot(aes(x = xvar, y = value, color = lsm, shape = model)) +
  geom_point(size = 3) +
  geom_text(
    data = facet_ranges,
    aes(x = -Inf, y = Inf, label = panel_label),
    inherit.aes = FALSE,
    hjust = -0.5,
    vjust = 1.5,
    color = "black"
  ) +
  geom_errorbar(
    data = facet_ranges,
    aes(x = xbar, ymin = min_value, ymax = max_value),
    inherit.aes = FALSE,
    width = 0.03 * x_range,
    color = "black"
  ) +
  geom_text(
    data = facet_ranges,
    aes(x = xtext, y = ymid, label = sprintf("%.0f", range_value)),
    inherit.aes = FALSE,
    angle = -90,
    hjust = 0.5,
    vjust = 0.5,
    color = "black"
  ) +
  facet_grid(
    variable ~ model, 
    scales = "free_y",
    switch = "y"
    ) +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  theme(
    strip.placement = "outside",
    strip.background = element_blank(),
    strip.text.y.left = element_text(angle = 90)
  ) +
  labs(
    x = "Cost-effective cum. LUC emissions since 2020 [GtCO2]",
    y = "",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
  )
ggsave("figB10_summary_2100_tbudget_1p7K50_dvgm.png", width = 9, height = 9)
ggsave("figB10_summary_2100_tbudget_1p7K50_dvgm.svg", width = 9, height = 9)

# Summary statistics for the figure
dum %>% 
  group_by(variable, model) %>%
  summarise(min = min(value), max = max(value), dif = max-min,mean = min(value), dpc = 100*dif/mean)


# Figure B11: Emissions over time (currently not on document=======================================
mixbigmif %>%
  filter(
    # cbudget == usebudget,
    region %in% c("GLO", "World")
    # lsm == model | model == "AR6"
  ) %>%
  filter(variable %in% c(
    "Emi|CO2|Gross|Energy and Industrial Processes",
    "Emi|CO2|CDR",
    "Emi|CO2"
  )) %>%
  mutate(value = value * 1e-3, unit = "GtCO2/yr") %>%
  filter_tbudget(tbudgetinfo) %>%
  left_join(tbudgetinfo) %>% #View
  # mutate(model = ifelse(model == "REMIND-MAgPIE", "Density effect", "Density + Budget effects")) %>%
  # select(model) %>% unique
  mutate(model = fct_relevel(model, "Density effect", "Density + Budget effects")) %>%
  mutate(variable = case_when(
    variable == "Emi|CO2|Gross|Energy and Industrial Processes" ~ "Gross FFI CO2 emissions\n[GtCO2/yr]",
    variable == "Emi|CO2|CDR" ~ "CDR\n[GtCO2/yr]",
    variable == "Emi|CO2" ~ "Net CO2 emissions\n[GtCO2/yr]",
    TRUE ~ variable
  )) %>%
  ggplot(aes(x = period, y = value, color = lsm, shape = model)) +
  geom_path() +
  geom_vline(xintercept = 2050, linetype = "dashed") +
  facet_grid(variable ~ model, scales = "free_y", switch = "y") +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(limits = c(2020, 2100)) +
  theme_bw() +
  theme(
    strip.placement = "outside",
    strip.background.y = element_blank(),
    strip.text.y.left = element_text(angle = 90)
  ) +
  labs(
    x = "",
    y = "",
    color = "DVGM",
    shape = ""
  )
ggsave("figB11_emissions_time.png", width = 8, height = 8)



bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      "Resources|Land Cover|+|Forest"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(cbudget == 560) %>%
  mutate(value = value - value[match(2020, period)]) %>%
  filter(period == 2050) %>%
  summarize(value = mean(value, na.rm = T)) 

# Figure B5: Illustrative Carbon prices =================================

# 1. Define region code to descriptive name mapping
region_map <- c(
  "CAZ" = "Canada, Australia & NZ",
  "CHA" = "China",
  "EUR" = "European Union",
  "IND" = "India",
  "JPN" = "Japan",
  "LAM" = "Latin America & Caribbean",
  "MEA" = "Middle East & North Africa",
  "NEU" = "Non-EU Europe",
  "OAS" = "Other Asia & Pacific",
  "REF" = "Reforming Economies",
  "SSA" = "Sub-Saharan Africa",
  "USA" = "United States"
)

# 2. Define a distinct 12-color palette mapped to human-readable names
# (Based on RColorBrewer 'Paired' palette for high visual distinction)
custom_palette <- c(
  "Canada, Australia & NZ"        = "#A6CEE3",
  "China"                         = "#1F78B4",
  "European Union"                = "#B2DF8A",
  "India"                         = "#33A02C",
  "Japan"                         = "#FB9A99",
  "Latin America & Caribbean"     = "#E31A1C",
  "Middle East & North Africa"    = "#FDBF6F",
  "Non-EU Europe"                 = "#FF7F00",
  "Other Asia & Pacific"          = "#CAB2D6",
  "Reforming Economies"           = "#6A3D9A",
  "Sub-Saharan Africa"            = "#B15928",
  "United States"                 = "#666666"
)

# 3. Data transformation and plotting
bigmif %>%
  filter(variable == "Price|Carbon") %>%
  filter(lsm == "LPJml") %>%
  filter(cbudget %in% c(600, 860)) %>%
  mutate(
    region_name = dplyr::recode(region, !!!region_map),
    cbudget_label = paste("Carbon Budget:", cbudget, " GtCO2"),
    label = NA_character_
  ) %>%
  {
    max_val <- max(.$value, na.rm = TRUE)
    bind_rows(
      .,
      tibble(cbudget = c(600, 860), period = 2023, value = max_val * 0.95) %>%
        mutate(
          cbudget_label = paste("Carbon Budget:", cbudget, " GtCO2"),
          label = c("a", "b"),
          region_name = NA_character_,
          region = NA_character_,
          variable = NA_character_,
          lsm = NA_character_
        )
    )
  } %>%
  ggplot(aes(x = period, y = value, color = region_name, group = region_name)) +
  geom_line(linewidth = 1, na.rm = TRUE) +
  # geom_point(size = 1.5) +
  geom_text(aes(label = label), size = 5, vjust = -0.5, hjust = -0.5, color = "black", na.rm = TRUE) +
  facet_wrap(~ cbudget_label) +
  scale_color_manual(values = custom_palette) +
  xlim(2020,2100) +
  labs(
    # title = "Carbon Price Trajectory by Region",
    x = "",
    y = "Carbon price (USD2017/tCO2)",
    color = "Region"
  ) +
  theme_bw() +
  theme(
    # strip.text = element_text(face = "bold", size = 11),
    legend.position = "bottom"
  )

ggsave("figB5_illustrative_cprice.png", width = 9, height = 5)

# Illustrative Stacked bar =================================
bigmif %>% select(lsm) %>% unique 

# Adjusting cumulative emissions to be since 2020 (default 2005)
# TODO: Check this against budgets
tempcumvars <- c(
    # "Emi|CO2|Cumulated",
    # "Emi|CO2|Cumulated|Energy and Industrial Processes",
    # "Emi|CO2|Cumulated|Land-Use Change"
    "Emi|CO2|Cum",
    "Emi|CO2|+|Energy|Cum",
    "Emi|CO2|+|Industrial Processes|Cum",
    "Emi|CO2|+|Land-Use Change|Cum",
    "Emi|CO2|+|Waste|Cum",
    "Emi|CO2|+|non-ES CDR|Cum"
  )
temp2020 <- bigmif %>% distinct() %>%
  filter(variable %in% tempcumvars, region %in% c("GLO")) %>% 
  filter(period == 2020) %>%
  select(scenario, variable, value) %>%
  rename(val2020 = value)
tempcumdata <- bigmif %>% distinct() %>%
  filter(variable %in% tempcumvars, region %in% c("GLO")) %>%
  mutate(value = value*1e-3) #%>% 
  # left_join(temp2020) %>%
  # mutate(value = value - val2020)

tempcumdata %>% select(variable) %>% unique
tempcumdata <-
  tempcumdata %>%
  calc_addVariable(
    `Emi|CO2|+|Energy and Industrial Processes|Cum` = "`Emi|CO2|+|Energy|Cum` + `Emi|CO2|+|Industrial Processes|Cum`",
    only.new = FALSE
    ) #%>% select(variable) %>% unique

pkemidata <- tempcumdata %>%
    filter(variable == "Emi|CO2|Cum", region == "GLO") %>%
  # filter(variable == "Emi|CO2|Cumulated", region == "GLO") %>%
  group_by(scenario) %>% 
  filter(value == max(value)) %>%
  select(scenario, value, period) %>%
  # mutate(value = value*1e-3) %>%
  rename(pkemival = value, pkemiyear = period)


temppkdata <-
  tempcumdata %>%
  filter(variable %in% c(
    # "Emi|CO2|Cumulated|Energy and Industrial Processes",
    # "Emi|CO2|Cumulated|Land-Use Change"
    "Emi|CO2|Cum",
    "Emi|CO2|+|Land-Use Change|Cum",
    "Emi|CO2|+|Energy and Industrial Processes|Cum"
  )) %>% #select(variable) %>% unique
  left_join(pkemidata) %>%
  filter(period == pkemiyear) %>%
  left_join(tbudgetinfo) %>%
  filter(cbudget == tbudgetdvgm)
temppkdata %>% select(variable) %>% unique

tempmeandata <- temppkdata %>%
  group_by(variable) %>%
  summarize(value = mean(value))

# Extra LUC variables
luctempcumvars <- c(
    "Emissions|CO2|Land RAW|Land-use Change|+++|Deforestation and Wood Harvest",
    "Emissions|CO2|Land RAW|Land-use Change|+++|Regrowth",
    "Emissions|CO2|Land RAW|Land-use Change|+++|Other LUC"
  )
luctemppkdata <- bigmif %>% 
  filter(variable %in% luctempcumvars, region %in% c("GLO","World")) %>%
  left_join(pkemidata) %>%
  filter(period == pkemiyear) %>%
  left_join(tbudgetinfo) %>%
  filter(cbudget == tbudgetdvgm) 

luctempmeandata <- luctemppkdata %>%
  group_by(variable) %>%
  summarize(value = mean(value))

# TODO: This is currently wrong, as the points are not lining
# up with the stacked bar. Fix in post for now.
tempmeandata %>% 
# temppkdata %>% 
  filter(!variable %in% c("Emi|CO2|Cum")) %>%
  # filter(scenario == "C_ESM2025v05-LPJml-SSP2-PkBudg620-rem-5") %>%
  # filter(lsm == "CABLEPOP") %>%
  # ggplot(aes(x = scenario, y = value, fill = variable)) +
  ggplot(aes(x = 1, y = value, fill = variable)) +
  geom_bar(position="stack", stat="identity") +
  geom_point(
    data = filter(
      temppkdata, 
      variable != "Emi|CO2|+|Energy and Industrial Processes|Cum"
      ), 
    size = 2,
    aes(x = 2, color = lsm)  
    ) +
  scale_color_manual(values = modelcolors) + 
  labs(
    y = "Peak Cumulative CO2 emissions since 2020 [GtCO2]",
    color = "DVGM"
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 16)
  )
# ggsave("illus_stackbar.png", width = 10, height = 12)
ggsave("illus_stackbar.svg", width = 6, height = 8)

# Just the LUC components
luctempmeandata %>% 
  filter(!variable %in% c("Emi|CO2|Cum")) %>%
  ggplot(aes(x = 1, y = value, fill = variable)) +
  geom_bar(position="stack", stat="identity") +
  geom_point(
    data = filter(
      luctemppkdata, 
      variable != "Emi|CO2|+|Energy and Industrial Processes|Cum"
      ), 
    size = 2,
    aes(x = 2, color = lsm)  
    ) +
  scale_color_manual(values = modelcolors) + 
  labs(
    y = "Cumulative LUC CO2 emissions at peak since 2020 [GtCO2]",
    color = "DVGM"
  ) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    axis.text = element_text(size = 16),
    axis.title = element_text(size = 16)
  )
# ggsave("illus_stackbar.png", width = 10, height = 12)
ggsave("illus_stackbar_luc.svg", width = 6, height = 8)


# Forest area at peak inset, DVGM-calibrated budget ==========================
tmpmif <- bigmif %>%
  filter(variable %in% c(
    # "Resources|Land Cover Change|+|Cropland",
    "Resources|Land Cover Change|+|Forest"
    # "Resources|Land Cover Change|+|Other Land",
    # "Resources|Land Cover Change|+|Pastures and Rangelands",
    # "Resources|Land Cover Change|+|Urban Area"
  ), region == "GLO") %>%
  # pivot_wider(names_from = variable, values_from = value) %>% # mutate(value = map_int(`Extracted NBP [Gtc/yr]`,length)) %>% filter(value != 1, period == 2000)
  # drop_na() %>%
    # left_join(sceninfo) %>%
  # filter(lsm == "LPJml") %>%
  left_join(tbudgetinfo) %>%
  left_join(pkemidata) %>%
  # filter(period == pkemiyear) 
  filter(period == 2050) 

bind_rows(
    tmpmif %>%
      filter(cbudget == tbudgetar6) %>%
      mutate(caltype = "LUC effect only"),
    tmpmif %>%
      filter(cbudget == tbudgetdvgm) %>%
      mutate(caltype = "Budget + LUC effect")
) %>%
  ggplot(aes(x = caltype, y = value, color = lsm)) +
  scale_color_manual(values = modelcolors) +
  geom_point() +
    theme_classic() +
  theme(
      axis.text.y = element_text(size = 16),
      axis.title.y = element_text(size = 16),
      axis.line.y = element_blank(),
      axis.text.x = element_text(size = 16),
      axis.title.x = element_text(size = 16),
      # axis.line.x = element_blank()
      axis.ticks.length.x = unit(-0.25, "cm")
  ) +
  coord_flip() +
  theme(legend.position = "bottom") +
  labs(x = "", y = "Cost-efficient forest area change 1995-2050 (Mha)", color = "DVGM") 
ggsave("figure_forestarea_inset.png", width = 10, height = 6)
ggsave("figure_forestarea_inset.svg", width = 10, height = 6)

# Scatter forest area LUC effect vs. Both effects
bind_rows(
  tmpmif %>%
    filter(cbudget == tbudgetar6) %>%
    mutate(caltype = "LUC effect only"),
  tmpmif %>%
    filter(cbudget == tbudgetdvgm) %>%
    mutate(caltype = "Budget + LUC effect")
) %>%
  select(variable,lsm, caltype, value) %>%
  pivot_wider(names_from = caltype) %>% 
  ggplot(aes(x = `LUC effect only`, y = `Budget + LUC effect`, color = lsm)) +
  scale_color_manual(values = modelcolors) +
  geom_point() +
  theme_classic() +
  facet_wrap(~variable)

# Split LUC with regrowth ==============
lucmif <-
  bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable %in% c(
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Deforestation",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Other land conversion",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Peatland",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Regrowth",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Residual",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Soil",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Timber",
    "Emissions|CO2|Land|Cumulative|Land-use Change|+|Wood Harvest"
  )) %>%
  filter(period == 2050) %>%
  mutate(grosspositive = ifelse(value >= 0, "Gross-positive LUC emission categories", "Gross-negative LUC emission categories")) %>%
  group_by(across(-c("variable", "value"))) %>%
  summarize(value = sum(value)) %>%
  ungroup %>%
  left_join(tbudgetinfo) %>%
  filter(cbudget == tbudgetdvgm) %>%
  mutate(variable = grosspositive)

p1 <- bind_rows(filter(tbudgetmif,model!="AR6"),lucmif) %>%
  select(variable, lsm, value) %>%
  pivot_wider(names_from = variable, values_from = value) %>% 
  ggplot(aes(y = `Carbon budget to 1.7C 50th perc.`, x = `Gross-positive LUC emission categories`, color = lsm)) +
  geom_point(size = 2) +
  scale_color_manual(values = modelcolors)
  
p2 <- bind_rows(filter(tbudgetmif,model!="AR6"),lucmif) %>%
  select(variable, lsm, value) %>%
  pivot_wider(names_from = variable, values_from = value) %>% 
  ggplot(aes(y = `Carbon budget to 1.7C 50th perc.`, x = `Gross-negative LUC emission categories`, color = lsm)) +
  geom_point(size = 2) +
  scale_color_manual(values = modelcolors)


cowplot::plot_grid(p1,p2)

# Scatterplots with input stocks ==========================================
# Stocks (MMAgPIE inputs)vs. Flows ==========================================
compdata <- histfluxmif %>%
  left_join(filter(allglostocks, landtype == "primforest")) %>%
  filter(variable == "nbp")  %>%
  ungroup

reg <- lm(value ~ vegc, data = compdata) 
summary(reg)
reg_coef <- coef(reg)
reg_summary <- summary(reg)
reg_pvalue <- reg_summary$coefficients["vegc", "Pr(>|t|)"]
reg_r_squared <- reg_summary$r.squared
reg_label <- paste0(
  "y = ", formatC(reg_coef["(Intercept)"], format = "e", digits = 2),
  " + ", formatC(reg_coef["cVeg"], format = "e", digits = 2), " * x\n",
  "p-value = ", sprintf("%.2f", reg_pvalue),
  ", R\u00b2 = ", sprintf("%.2f", reg_r_squared)
)

p1 <- compdata %>%
  ggplot(aes(x = vegc, y = value)) +
  geom_point(aes(color = lsm)) +
  geom_smooth(aes(group = NULL),method = "lm") +
  annotate("text", x = -Inf, y = Inf, label = reg_label, hjust = -0.05, vjust = 1.1) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Area-weighted average primary forest\nC density potential [tCO2/ha]",
    y = "Global atmosphere-to-land CO2 flux\naverage 1960-2020 [GtCO2/yr]",
    color = "DGVM"
  ) +
  ylim(3,13) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal"
  ) 
print(p1)
ggsave("input_stock_vs_flow_magpie.png", width = 7, height = 5)


lm(value ~ vegc, data = compdata) %>% summary
# cor(compdata$value,compdata$vegc)

# Stocks (MAGICC calib) vs. Flows ==========================================


plotmif <- histfluxmif %>%
  filter(variable %in% c("nbp","cVeg")) %>%
  select(-unit) %>%
  pivot_wider(names_from = "variable", values_from = "value") 
reg <- lm(nbp ~ cVeg, data = plotmif) 
summary(reg)
reg_coef <- coef(reg)
reg_summary <- summary(reg)
reg_pvalue <- reg_summary$coefficients["cVeg", "Pr(>|t|)"]
reg_r_squared <- reg_summary$r.squared
reg_label <- paste0(
  "y = ", formatC(reg_coef["(Intercept)"], format = "e", digits = 2),
  " + ", formatC(reg_coef["cVeg"], format = "e", digits = 2), " * x\n",
  "p-value = ", sprintf("%.2f", reg_pvalue),
  ", R\u00b2 = ", sprintf("%.2f", reg_r_squared)
)

p2 <- plotmif %>%
  ggplot(aes(x = cVeg, y = nbp)) +
  geom_point(aes(color = lsm)) +
  geom_smooth(aes(group = NULL),method = "lm") +
  annotate("text", x = -Inf, y = Inf, label = reg_label, hjust = -0.05, vjust = 1.1) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Global vegetation carbon stock\naverage 1960-2020 [GtCO2]",
    y = "Global atmosphere-to-land CO2 flux\naverage 1960-2020 [GtCO2/yr]",
    color = "DGVM"
  ) +
  ylim(3,13) +
  theme_classic() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal"
  ) 
print(p2)
ggsave("input_stock_vs_flow_magicc.png", width = 7, height = 5)



leg <- get_legend(p1)
p1 <- p1 + theme(legend.position = "none")
p2 <- p2 + theme(legend.position = "none")

# pcomb <- cowplot::plot_grid(p1,p2)
pcomb <- cowplot::plot_grid(p1,NULL,p2, ncol = 3, rel_widths = c(1,0.05,1)) # Add a bit of space between plots
cowplot::plot_grid(pcomb, leg, ncol = 1, rel_heights = c(1,0.2)) + 
  theme(plot.background = element_rect(fill = "white", color = NA))
ggsave("correlation_inputs.png", width = 10, height = 5)


# LUC with input stocks ==========================================

xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
lucmif <-
  bigmif %>%
  filter(region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar) %>%
  filter_tbudget(tbudgetinfo)

allglostocks %>%
  filter(landtype == "primforest") %>%
  select(lsm, vegc, totc) %>%
  left_join(lucmif) %>% 
  drop_na() %>% 
  pivot_longer(cols = c("totc", "vegc")) %>%
  mutate(name = replace_when(name,
                             name == "totc" ~ "Land + Litter + Soil",
                             name == "vegc" ~ "Vegetation"
                             )) %>%
  mutate(value = value*3.66) %>% # tC/ha to tCO2/ha
  ggplot(aes(x = value, y = xvar, color = lsm)) +
  geom_point() +
  labs(
    x = "Global area-weighted average C potential\nof vegetation pool or total land pool [tCO2/ha]",
    y = "Cost-effective cum. LUC emissions 2020-2050 [GtCO2]",
    color = "DGVM"
      ) +
  scale_color_manual(values = modelcolors) + 
  theme_bw() +
  facet_wrap(~name+model, scales = "free")
ggsave("density_vs_luc.png", width = 8, height = 6)
ggsave("density_vs_luc.svg", width = 8, height = 6)


# Summary with input stocks ==========================================

xmif <- allglostocks %>%
  filter(landtype == "primforest") %>%
  select(lsm, vegc) %>%
  rename(xvar = vegc)

combmif <- mixbigmif %>%
  filter(
    # cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>%
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest Area in 2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2050" ~ "Cum. Gross FFI CO2 emi. in 2050 [GtCO2]",
    variable == "Price|Carbon in 2050" ~ "Carbon Price in 2050 [$/tCO2]",
    # variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2050" ~ "Total cum. CDR in 2050 [$/tCO2]",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>% 
  left_join(tbudgetinfo) %>%
  filter_tbudget(tbudgetinfo)

combmif %>%
  bind_rows(
    tbudgetmif %>%
      mutate(model = ifelse(model == "AR6","AR6 Ensemble","Calibrated to DVGM")) %>%
      left_join(xmif)
  ) %>%     
  mutate(variable = str_replace(variable, " in 20", "\n20")) %>%
  mutate(variable = str_replace(variable, " to 1.7C", "\nto 1.7°C")) %>%
  # ggplot(aes(x = lsm, y = value, color = lsm, shape = model, group = lsm)) +
  ggplot(aes(x = xvar, y = value, color = lsm, shape = model)) +
  geom_point(size = 3) +
  # geom_line() +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # coord_flip() +
  facet_wrap(~ variable + model, scales = "free", ncol = 2) +
  # facet_grid(variable ~ model, scales = "free") +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  labs(
    x = "Global area-weighted average C potential [tCO2/ha]",
    y = "",
    shape = "Climate parametrization",
    color = "C densities from DVGM:"
  )
ggsave("summary_tbudget_stocks_1p7K50_dvgm.png", width = 8, height = 10)
ggsave("summary_tbudget_stocks_1p7K50_dvgm.svg", width = 8, height = 10)

# Prices vs. budget =============================================================
combmif %>%
  filter(model != "AR6 Ensemble") %>% 
  select(-unit) %>%
  pivot_wider(names_from = "variable", values_from = "value") %>%
  ggplot(aes(y = `Carbon Price in 2050 [$/tCO2]`, x = cbudget, color = lsm)) +
  geom_point(size = 3) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Carbon budget to 1.7°C 50th perc [GtCO2]",
    color = "DVGM:"
  ) +
  theme_classic()
  
ggsave("budget_vs_price_1p7K50_dvgm.png", width = 6, height = 5)


# ====================================================================
# AR6 ensemble plot to check if using budgets is ok
mixbigmif %>%
  filter(
    region == "World",
    variable == "Surface Air Temperature Change|q67"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  filter(lsm == model | model == "AR6") %>%
  mutate(caltype = ifelse(model != "AR6", "Calibrated_to_DVGM", "AR6 Ensemble")) %>%
  filter(caltype == "AR6 Ensemble") %>%
  select(scenario, period, value, cbudget, lsm, caltype) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  group_by(scenario, caltype) %>%
  filter(value == max(value, na.rm = T)) %>%
  ungroup() %>%
  # filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  # filter(lsm %in% illumodels) %>%
  ggplot(aes(
    x = cbudget, y = value,
    color = lsm,
    lty = caltype, shape = caltype
  )) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Peak GSAT 67th perc. [K]"),
    shape = "Climate model calibration:",
    lty = "Climate model calibration:",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(500, 720, by = 20))

# ====================================================================
# Checking airborne fraction calculation
mixbigmif %>%
  filter(variable %in% c(
    "Harmonized|Emissions|CO2|Cum",
    "Atmospheric Concentrations|CO2|EqEm2020|q50",
    "Airborne Fraction|Since2020|q50"
  )) %>%
  mutate(value = ifelse(
    variable == "Airborne Fraction|Since2020|q50",
    ifelse(value < (-0.5), NA, value) * 100,
    value * 1e-3
  )) %>%
  filter(period <= 2100) %>%
  filter(policy == "PkBudg600") %>%
  filter(lsm == "LPJml") %>%
  filter(period == 2040) %>%
  select(variable, model, value) %>%
  print(n = 1000)
# ggplot(aes(x = period, y = value, color = model)) +
#   geom_line() +
#   facet_wrap(~variable, scales = "free_y", ncol = 1)

# ====================================================================
# REMIND-MAgPIE only plots
# ====================================================================

# ===================================================================
# Summary plots

# Basic summary plots
usebudget <- musebudget
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      "Resources|Land Cover|+|Forest",
      "Emi|CO2|+|Energy|Cum",
      "Emi|CO2|+|Land-Use Change|Cum",
      "Price|Carbon"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget == usebudget) %>%
  ggplot(aes(x = lsm, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "",
    color = "C densities from DVGM:"
  )

# Summary vs. LUC emissions

xvarname <- "Emi|CO2|+|Land-Use Change|Cum"
xmif <- bigmif %>%
  filter(cbudget == usebudget, region %in% c("GLO", "World")) %>% # select(variable) %>% unique %>% print(n=1000)
  filter(variable == xvarname) %>%
  filter(period == 2050) %>%
  mutate(variable = ifelse(variable == xvarname, "xvar", variable)) %>%
  mutate(value = ifelse(variable == "xvar", value * 1e-3, value)) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # select(scenario,period,cbudget, lsm, xvar)
  select(scenario, cbudget, lsm, xvar)

mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Resources|Land Cover|+|Forest in 2050" ~ "Forest Area in 2050 [Mha]",
    # variable == "Resources|Land Cover|+|Forest in 2100" ~ "Forest Area in 2100 [Mha]",
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes in 2050" ~ "Cum. Gross FFI CO2 emissions in 2050 [GtCO2]",
    variable == "Price|Carbon in 2050" ~ "Carbon Price in 2050 [$/tCO2]",
    variable == "Price|Carbon in 2030" ~ "Carbon Price in 2030 [$/tCO2]",
    variable == "Emi|CO2|Cumulated|CDR in 2050" ~ "Total cum. CDR in 2050 [$/tCO2]",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  # filter(str_detect(policy, "PkBudg")) %>%
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()
ggsave(paste0("summary_Xlucemi2050_", usebudget, ".png"), width = 10, height = 7)
ggsave(paste0("summary_Xlucemi2050_", usebudget, ".svg"), width = 10, height = 7)


mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  filter(variable %in% c(
    "Harmonized|Emissions|CO2|Cum",
    "Surface Air Temperature Change|q67",
    "Effective Radiative Forcing|q67",
    "Effective Radiative Forcing|CH4|q67",
    "Effective Radiative Forcing|N2O|q67",
    "Effective Radiative Forcing|CO2|q67"
  ), model %in% c("AR6","REMIND-MAgPIE","REMIND")) %>%
  left_join(nzmif) %>%
  filter(period == nzyearharm) %>%
  mutate(variable = paste0(variable, " at net-zero")) %>%
  left_join(xmif) %>% #select(variable) %>% unique
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()

mixbigmif %>%
  filter(
    cbudget == usebudget,
    region %in% c("GLO", "World")
  ) %>%
  left_join(xmif) %>% # filter(variable %in% c("Emi|CO2","Price|Carbon"), period == 2050, lsm == "LPJml")
  mutate(value = case_when(
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes" ~ value * 1e-3, # MtCO2 to GtCO2
    variable == "Emi|CO2|Cumulated|CDR" ~ value * -1e-3, # MtCO2 to GtCO2
    TRUE ~ value
  )) %>% 
  mutate(variable = paste0(variable, " in ", period)) %>%
  mutate(variable = case_when(
    variable == "Harmonized|Emissions|CO2|Cum in 2050" ~ "Cum. CO2 emissions in 2050 [$/tCO2]",
    variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    # variable == "Surface Air Temperature Change|q67 in 2050" & model == "AR6" ~ "GSAT in 2050 (67th perc.)",
    TRUE ~ NA
  )) %>%
  filter(!is.na(variable)) %>%
  # filter(str_detect(policy, "PkBudg")) %>%
  ggplot(aes(x = xvar, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  facet_wrap(~variable, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "Cum. LUC emissions 2020-2050 [GtCO2]",
    y = "",
    color = "C densities from DVGM:"
  ) +
  theme_bw()
ggsave(paste0("summaryclim_Xlucemi2050_", usebudget, ".png"), width = 10, height = 7)

# CDR Summary plots
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    variable %in% c(
      # "Emi|CO2|CDR",
      # "Emi|CO2|CDR|+|BECCS",
      # "Emi|CO2|CDR|+|DACCS",
      # # "Emi|CO2|CDR|+|EW",
      # "Emi|CO2|CDR|+|Land-Use Change"
      # # "Price|Carbon"
      "Emi|CO2|Cumulated|CDR",
      "Emi|CO2|Cumulated|CDR|BECCS",
      # "Emi|CO2|Cumulated|CDR|BECCS|Demand Side",
      # "Emi|CO2|Cumulated|CDR|BECCS|Pe2Se",
      "Emi|CO2|Cumulated|CDR|DACCS",
      # "Emi|CO2|Cumulated|CDR|EW",
      "Emi|CO2|Cumulated|CDR|Land-Use Change"
    )
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  mutate(variable = paste0(variable, " [", unit, "]")) %>%
  filter(period %in% c(2050, 2100)) %>%
  filter(cbudget == usebudget) %>%
  ggplot(aes(x = lsm, y = value, color = lsm)) +
  geom_point(size = 3) +
  # theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  coord_flip() +
  facet_wrap(~ variable + period, scales = "fixed", ncol = 2) +
  # facet_wrap(~variable+period, scales = "free", ncol = 2) +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "",
    color = "C densities from DVGM:"
  )


# Temp vs. budgets
useyear <- 2100
bigmif %>%
  filter(
    region == "GLO",
    variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    # variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("GSAT ", useyear, " 67th perc. [K]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  # ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 20))



# Prices vs. budgets
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Price|Carbon"
  ) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  group_by(scenario, cbudget, lsm) %>%
  summarise(peakprice = max(value, na.rm = T)) %>%
  ungroup() %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = peakprice, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = "Carbon Price at net-zero [USD2017/tCO2]",
    color = "C densities from DVGM:"
  ) +
  scale_y_continuous(
    breaks = seq(0, 3000, by = 100),
    minor_breaks = seq(0, 3000, by = 25)
  ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXprice.png")
ggsave("budgetXprice.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Emi|CO2|+|Land-Use Change|Cum"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  # filter(lsm == "LPJml") %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  # theme(legend.position = "bottom", legend.orientation = "horizontal") +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXlucemi.png")
ggsave("budgetXlucemi.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    # variable == "Emi|CO2|+|Energy|Cum"
    variable == "Emi|CO2|Cumulated|Gross|Energy and Industrial Processes"
  ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  # theme(legend.position = "bottom", legend.orientation = "horizontal") +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative gross energy and industry CO2 emissions\n2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXeneemi.png")
ggsave("budgetXeneemi.svg")


# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(region == "World") %>%
  calc_addVariable(
    emiffi = "`Emi|CO2|+|Land-Use Change|Cum` +
            `Emi|CO2|+|Energy|Cum` +
    `Emi|CO2|+|Industrial Processes|Cum` +
    `Emi|CO2|+|Waste|Cum` +
    `Emi|CO2|+|non-ES CDR|Cum`"
  ) %>%
  filter(variable == "emiffi") %>%
  # filter(
  #     region == "World",
  #     # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
  #     variable == "Emi|CO2|+|Land-Use Change|Cum"
  # ) %>%
  mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(cbudget >= 600) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Cumulative LUC emissions 2020-", useyear, " [GtCO2]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXffiemi.png")
ggsave("budgetXffiemi.svg")



# Prices vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Resources|Land Cover|+|Forest"
  ) %>%
  # mutate(value = value * 1e-3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(between(cbudget, mlowbudget, mhigbudget)) %>%
  # group_by(cbudget) %>% summarise(minval = min(value), maxval = max(value)) %>% mutate(diff = maxval-minval)
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("Global forest area in ", useyear, " [Mha]"),
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(mlowbudget, mhigbudget, by = 40))
ggsave("budgetXforest.png")
ggsave("budgetXforest.svg")


# CDR vs. cumulative LUC
useyear <- 2050
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable == "Emi|CO2|CDR"
  ) %>%
  mutate(value = value * 1e3) %>%
  filter(str_detect(policy, "PkBudg")) %>%
  select(scenario, period, value, cbudget, lsm) %>%
  # group_by(scenario,cbudget, lsm) %>%
  # summarise(peakprice = max(value, na.rm = T)) %>%
  # ungroup() %>%
  filter(period == useyear) %>%
  mutate(cbudget = as.numeric(cbudget)) %>%
  filter(cbudget >= 600) %>%
  ggplot(aes(x = cbudget, y = value, color = lsm)) +
  geom_point(size = 3) +
  geom_line() +
  # geom_smooth(se = F, method = "loess") +
  theme_bw() +
  labs(
    x = "Carbon Budget from 2020 [GtCO2]",
    y = paste0("CDR deployment in", useyear, " [GtCO2/yr]"),
    color = "C densities from DVGM:"
  ) +
  scale_color_manual(values = modelcolors) +
  scale_x_continuous(breaks = seq(600, 720, by = 20))

# CDR breakdown for selected budgets =========================================

tot <- "Emi|CO2|CDR"
items <- c(
  "Emi|CO2|CDR|+|BECCS",
  "Emi|CO2|CDR|+|DACCS",
  "Emi|CO2|CDR|+|EW",
  "Emi|CO2|CDR|+|Land-Use Change",
  "Emi|CO2|CDR|+|Materials",
  "Emi|CO2|CDR|+|OAE",
  "Emi|CO2|CDR|+|Synthetic Fuels CCS"
)
plt <- bigmif %>%
  filter(variable %in% c(tot, items)) %>%
  filter(cbudget == usebudget) %>%
  filter(region == "GLO") %>%
  createAreaAndBarPlots(items, tot, mainReg = "GLO", , yearsBarPlot = c(2050, 2100), scales = "fixed")
plt
  # showAreaAndBarPlots(items, tot, mainReg = "GLO", , yearsBarPlot = c(2050, 2100), scales = "fixed")
ggsave(paste0("cdr_bars_",usebudget,".png"), width = 14, height = 5)

tot <- "Emi|CO2|Cumulated|CDR"
items <- c(
  "Emi|CO2|Cumulated|CDR|BECCS",
  "Emi|CO2|Cumulated|CDR|DACCS",
  "Emi|CO2|Cumulated|CDR|EW",
  "Emi|CO2|Cumulated|CDR|Land-Use Change",
  "Emi|CO2|Cumulated|CDR|Materials",
  "Emi|CO2|Cumulated|CDR|OAE",
  "Emi|CO2|Cumulated|CDR|Synthetic Fuels CCS"
)

usemif <- bigmif %>%
  filter(variable %in% c(tot, items)) %>%
  filter(cbudget == usebudget) %>%
  filter(region == "GLO") %>%
  group_by(across(!c(period, value))) %>% # rebase the cumulative series to 2020
  arrange(period, .by_group = TRUE) %>%
  mutate(value = value - value[match(2020, period)]) %>%
  ungroup()

# plt <- bigmif %>%
#   filter(variable %in% c(tot, items)) %>%
#   filter(cbudget == usebudget) %>%
#   filter(region == "GLO") %>%
#   createAreaAndBarPlots(items, tot, mainReg = "GLO", , yearsBarPlot = c(2050, 2100), scales = "fixed")
# plt

usemif %>%
  filter(variable %in% items) %>% # components only, tot would double-count
  filter(period %in% c(2050, 2100)) %>%
  mutate(value = value * 1e-3 * -1) %>% # MtCO2 to GtCO2 and make positive
  mutate(variable = str_remove(variable, fixed("Emi|CO2|Cumulated|CDR|"))) %>%
  ggplot(aes(x = lsm, y = value, fill = variable)) +
  geom_col() +
  facet_wrap(~period, scales = "free_y") +
  scale_fill_manual(values = cdrcolors) +
  theme_bw() +
  labs(
    x = "",
    y = "Cumulative CDR since 2020 [GtCO2]",
    fill = "CDR type"
  ) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = rel(1.0))
  )
ggsave("cdr_stacked_bars.png", width = 8, height = 5)


# ===================================================================
# CDR isoline plots
# ===================================================================

useyears <- c(2050, 2100)
usebudget <- musebudget

xvarname <- "Emi|CO2|Cumulated|CDR|Land-Use Change"
yvarname <- "Emi|CO2|Cumulated|CDR|BECCS"
zvarname <- "Emi|CO2|Cumulated|CDR"
bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable %in% c(xvarname, yvarname, zvarname)
  ) %>%
  mutate(value = value * 1e-3 * -1) %>% # MtCO2 to GtCO2 and make positive
  filter(str_detect(policy, "PkBudg")) %>%
  filter(cbudget == usebudget) %>%
  mutate(variable = case_when(
    variable == xvarname ~ "xvar",
    variable == yvarname ~ "yvar",
    variable == zvarname ~ "zvar"
  )) %>%
  select(scenario, period, variable, value, cbudget, lsm) %>%
  filter(period %in% useyears) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  ggplot(aes(x = xvar, y = yvar, color = lsm)) +
  geom_textabline(
    aes(intercept = alpha, slope = beta, label = alpha),
    color = "grey70",
    data = data.frame(alpha = seq(0, 1000, 20), beta = -1)
  ) +
  geom_abline(aes(intercept = zvar, slope = -1, color = lsm)) +
  # geom_abline(intercept = seq(0,1000,10), slope = -1, color = "grey70") +
  geom_point(size = 3) +
  theme_bw() +
  labs(
    x = "Cumulative LUC CDR since 2020 [GtCO2]",
    y = "Cumulative BECCS CDR since 2020 [GtCO2]",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  facet_wrap(~period, scales = "free") +
  scale_color_manual(values = modelcolors)
# theme(legend.position = "bottom", legend.orientation = "horizontal") +
# scale_x_continuous(breaks = seq(600, 720, by = 20))
ggsave("cdr_isolines.png", height = 4, width = 10)
ggsave("cdr_isolines.svg", height = 4, width = 10)

# CDR isoline plots, updated
# ===================================================================

useyears <- c(2050, 2100)
usebudget <- musebudget

xvarname <- "Emi|CO2|Cumulated|CDR|Land-Use Change"
yvarname <- "Emi|CO2|Cumulated|CDR|BECCS"
zvarname <- "Emi|CO2|Cumulated|CDR"
cdrdata <- bigmif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable %in% c(xvarname, yvarname, zvarname)
  ) %>%
  mutate(value = value * 1e-3 * -1) %>% # MtCO2 to GtCO2 and make positive
  filter(str_detect(policy, "PkBudg")) %>%
  filter(cbudget == usebudget) %>%
  group_by(across(!c(period, value))) %>% # rebase the cumulative series to 2020
  arrange(period, .by_group = TRUE) %>%
  mutate(value = value - value[match(2020, period)]) %>%
  ungroup() %>%
  mutate(variable = case_when(
    variable == xvarname ~ "xvar",
    variable == yvarname ~ "yvar",
    variable == zvarname ~ "zvar"
  )) %>%
  select(scenario, period, variable, value, cbudget, lsm) %>%
  filter(period %in% useyears) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  mutate(rvar = zvar -(yvar + xvar)) 

cdrdata %>%
  # mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  ggplot(aes(x = xvar, y = yvar, color = lsm)) +
  geom_textabline(
    aes(intercept = alpha, slope = beta, label = alpha),
    color = "grey70",
    data = data.frame(alpha = seq(20, 1000, 40), beta = -1)
  ) +
  geom_abline(aes(intercept = zvar, slope = -1, color = lsm), show.legend = FALSE) +
  # geom_abline(intercept = seq(0,1000,10), slope = -1, color = "grey70") +
  geom_point(size = 3) +
  geom_segment(
      aes(x = xvar, y = yvar, xend = xvar + rvar, yend = yvar),
      # color = "grey70",
      linewidth = 0.1,
      # linetype = "dashed"
      show.legend = FALSE
    ) +
  geom_text(aes(
    x = xvar + rvar/2, y = yvar,
    label = round(rvar,0)
    ),
    vjust = -0.5, # bottom-aligned: text sits above y
    size = 0.8 * 3.88, # 3.88mm is the geom_text default
    show.legend = FALSE
    ) +
  theme_bw() +
  labs(
    x = "Cumulative LUC CDR since 2020 [GtCO2]",
    y = "Cumulative BECCS CDR since 2020 [GtCO2]",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  facet_wrap(~period, scales = "free") +
  # pad each panel by 10% of its own data range (default is 5%)
  scale_x_continuous(expand = expansion(mult = 0.1)) +
  scale_y_continuous(expand = expansion(mult = 0.1)) +
  scale_color_manual(values = modelcolors) +
  theme_bw() +
  theme(
    legend.position = "bottom",
    legend.direction = "horizontal",
    strip.background = element_blank(),
    strip.text = element_text(face = "bold", size = rel(1.0))
    )
# scale_x_continuous(breaks = seq(600, 720, by = 20))
ggsave("cdr_isolines_v2.png", height = 6*0.8, width = 10*0.8)
ggsave("cdr_isolines_v2.svg", height = 6*0.8, width = 10*0.8)



# ===================================================================
# CDR isoline plots, area
# ===================================================================

useyears <- c(2050, 2100)
usebudget <- musebudget


str(bigmif)

str(armif)

armif <- bigmif %>%
  filter(
    region == "GLO",
    variable %in% c(
      "Resources|Land Cover Change|Forest|Planted Forest|Natural|+|CO2-price AR",
      "Resources|Land Cover Change|Forest|Planted Forest|Plantations|+|CO2-price AR"
    )) %>%
    calc_addVariable(
      "Resources|Land Cover Change|Forest|Planted Forest|CO2-price AR" = "`Resources|Land Cover Change|Forest|Planted Forest|Natural|+|CO2-price AR` + `Resources|Land Cover Change|Forest|Planted Forest|Natural|+|CO2-price AR`",
      units = "million ha wrt 1995", only.new = T
    ) #%>%

usemif <- bigmif %>%
  filter(
    region == "GLO",
    variable %in% c(
      "Resources|Land Cover|Cropland|Croparea|+|Bioenergy crops"
    )) %>%
    bind_rows(armif) %>%
    rebase_to_period(ref_period = 2020) %>%
    calc_addVariable(
      "Land Cover Change|CO2-price AR and Bioenergy crops" = "`Resources|Land Cover|Cropland|Croparea|+|Bioenergy crops` + `Resources|Land Cover Change|Forest|Planted Forest|CO2-price AR`",
      units = "million ha wrt 2020", only.new = F
    ) 


xvarname <- "Resources|Land Cover Change|Forest|Planted Forest|CO2-price AR"
yvarname <- "Resources|Land Cover|Cropland|Croparea|+|Bioenergy crops"
zvarname <- "Land Cover Change|CO2-price AR and Bioenergy crops"

usemif %>%
  filter(
    region == "GLO",
    # variable == "MAGICC7 AR6|Surface Temperature (GSAT)|67p0th Percentile"
    variable %in% c(xvarname, yvarname, zvarname)
  ) %>%
  # mutate(value = value * 1e-3 * -1) %>% # MtCO2 to GtCO2 and make positive
  filter(str_detect(policy, "PkBudg")) %>%
  filter(cbudget == usebudget) %>%
  mutate(variable = case_when(
    variable == xvarname ~ "xvar",
    variable == yvarname ~ "yvar",
    variable == zvarname ~ "zvar"
  )) %>%
  select(scenario, period, variable, value, cbudget, lsm) %>%
  filter(period %in% useyears) %>%
  pivot_wider(names_from = variable, values_from = value) %>%
  # mutate(cbudget = as.numeric(cbudget)) %>%
  # filter(cbudget >= 600) %>%
  ggplot(aes(x = xvar, y = yvar, color = lsm)) +
  geom_textabline(
    aes(intercept = alpha, slope = beta, label = alpha),
    color = "grey70",
    data = data.frame(alpha = seq(0, 1000, 20), beta = -1)
  ) +
  geom_abline(aes(intercept = zvar, slope = -1, color = lsm)) +
  # geom_abline(intercept = seq(0,1000,10), slope = -1, color = "grey70") +
  geom_point(size = 3) +
  theme_bw() +
  labs(
    x = "CO2-induced afforetation since 2020 [MHa]",
    y = "New area for bioenergy crops since 2020 [MHa]",
    color = "C densities from DVGM:"
  ) +
  # scale_y_continuous(
  #     breaks = seq(400, 1000, by = 100),
  #     minor_breaks = seq(400, 1000, by = 25)
  #     ) +
  # geom_hline(yintercept = 0) +
  facet_wrap(~period, scales = "free") +
  scale_color_manual(values = modelcolors)
# theme(legend.position = "bottom", legend.orientation = "horizontal") +
# scale_x_continuous(breaks = seq(600, 720, by = 20))
ggsave("cdr_isolines_area.png", height = 4, width = 10)
ggsave("cdr_isolines_area.svg", height = 4, width = 10)


# Figure B3: Transition indicators ==============================================
bigmif %>%
  filter(
    region %in% c("GLO", "World"),
    # scenario %in% c(
    #   "C_ESM2025v05-LPJml-SSP2-PkBudg840-rem-5",
    #   "C_ESM2025v05-ORCHIDEE-SSP2-PkBudg840-rem-5"
    # ),
    cbudget == musebudget,
    variable %in% c(
      # "FE|Transport|Fuels|Share",
      # "FE|Transport|Electricity|Share",
      "PE|Fossil",
      # "PE|+|Coal",
      "FE|Electricity|Share",
      "PE",
      "Emi|CO2"
  )) %>%
  calc_addVariable("PE share of fossils [%]" = "100*`PE|Fossil`/`PE`") %>%
  filter(!(variable %in% c(
    "PE",
    "PE|Fossil"
  ))) %>%
  mutate(variable = case_when(
    # variable == "FE|Transport|Fuels|Share" ~ "Share (%)",
    # variable == "FE|Transport|Electricity|Share" ~ "Electrification share of transport [%]",
    # variable == "PE|Fossil" ~ "Primary energy from fossil fuels [EJ/yr]",
    # variable == "PE|+|Coal" ~ "Primary energy from coal [EJ/yr]",
    variable == "Emi|CO2" ~ "Total CO2 emissions [MtCO2/yr]",
    variable == "FE|Electricity|Share" ~ "Electricity share of final energy [%]",
    TRUE ~ variable
  )) %>% #filter(period == 2040) %>% arrange(variable) %>% print(n=1000)
  filter(between(period, 2025, 2070)) %>%
  ggplot(aes(x = period, y = value, color = lsm)) +
  geom_line() +
  scale_color_manual(values = modelcolors) +
  labs(
    x = "",
    y = "Share, EJ/yr or MtCO2/yr",
    color = "C densities from DVGM:"
  ) +
  theme_bw() +
  theme(legend.position = "bottom", legend.direction = "horizontal") +
  facet_wrap(~variable, scales = "free_y")
ggsave("figB3_transition_indicators.png", width = 10, height = 5)
ggsave("figB3_transition_indicators.svg", width = 10, height = 5)


# ===================================================================
# Scratch
# ===================================================================